//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_monitor_log
    {
        public int id { get; set; }
        public string change_operator { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string create_operator { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string delete_operator { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> log_tag { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string pin { get; set; }
        public string card_no { get; set; }
        public Nullable<int> device_id { get; set; }
        public string device_sn { get; set; }
        public string device_name { get; set; }
        public Nullable<int> verified { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> event_type { get; set; }
        public string description { get; set; }
        public Nullable<int> event_point_type { get; set; }
        public Nullable<int> event_point_id { get; set; }
        public string event_point_name { get; set; }
    }
}
