//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActFijoValores20181018
    {
        public string ActFijoCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ActFijoAno { get; set; }
        public Nullable<System.DateTime> ActFijoFechaIng { get; set; }
        public Nullable<double> ActFijoNetoOriTrib { get; set; }
        public Nullable<double> ActFijoNetoOriCont { get; set; }
        public Nullable<double> ActFijoResOriTrib { get; set; }
        public Nullable<double> ActFijoResOriCont { get; set; }
        public Nullable<short> ActFijoVidaUtilTrib { get; set; }
        public Nullable<short> ActFijoVidaUtilCont { get; set; }
        public Nullable<double> ActFijoNetoPerTrib { get; set; }
        public Nullable<double> ActFijoNetoPerCont { get; set; }
        public Nullable<double> ActFijoResPerTrib { get; set; }
        public Nullable<double> ActFijoResPerCont { get; set; }
        public Nullable<short> ActFijoVidaPerTrib { get; set; }
        public Nullable<short> ActFijoVidaPerCont { get; set; }
        public Nullable<double> ActFijoDepPerTrib { get; set; }
        public Nullable<double> ActFijoDepPerCont { get; set; }
        public Nullable<double> ActFijoNetoActTrib { get; set; }
        public Nullable<double> ActFijoNetoActCont { get; set; }
        public Nullable<double> ActFijoResActTrib { get; set; }
        public Nullable<double> ActFijoResActCont { get; set; }
        public Nullable<double> ActFijoDepActTrib { get; set; }
        public Nullable<double> ActFijoDepActCont { get; set; }
        public Nullable<short> ActFijoVidaRestTrib { get; set; }
        public Nullable<short> ActFijoVidaRestCont { get; set; }
        public Nullable<System.DateTime> ActFijoUltProceso { get; set; }
        public Nullable<short> ActFijoUltimo { get; set; }
    }
}
