//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivosFijosUltimo
    {
        public string ActFijoCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ActFijoAno { get; set; }
        public string ActFijoDescripcion { get; set; }
        public string SucuCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string AtribDesUbicacion { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<short> CtaCAno { get; set; }
        public string CodRCodigo { get; set; }
        public string AtribCtaCorreccion { get; set; }
        public string AtribCtaDepreciacion { get; set; }
        public string AtribCtaDepAcumulada { get; set; }
        public string AtribFoto { get; set; }
        public Nullable<int> AtribTipoDepreciacion { get; set; }
        public Nullable<short> AtribCuatroPor { get; set; }
        public string cogeCodigo { get; set; }
        public string TiafCodigo { get; set; }
        public Nullable<short> ActFijoDadoDeBaja { get; set; }
    }
}
