//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicione
    {
        public string EmprCod { get; set; }
        public int AdicNumero { get; set; }
        public Nullable<System.DateTime> AdicFecha { get; set; }
        public Nullable<double> AdicTotal { get; set; }
        public Nullable<short> AdicEmitida { get; set; }
        public string EmplRutF { get; set; }
        public Nullable<short> EmplExtranjero { get; set; }
        public string mesaCodigo { get; set; }
        public Nullable<double> AdicTotalSD { get; set; }
        public Nullable<int> AdicEsSistema { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
    }
}
