//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuste_lotes_detalle
    {
        public string EmprCod { get; set; }
        public double AjusteId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Mes { get; set; }
        public string Ano { get; set; }
        public string Usuario { get; set; }
        public Nullable<double> MostNro { get; set; }
        public string ProdCodigo { get; set; }
        public string ProdNombre { get; set; }
        public string Observacion { get; set; }
        public string AlmaCodigo { get; set; }
        public string Lote { get; set; }
        public Nullable<double> StockTeorico { get; set; }
        public Nullable<double> StockFisico { get; set; }
        public Nullable<System.DateTime> FechaVenc { get; set; }
    }
}
