//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacene
    {
        public string AlmaCodigo { get; set; }
        public string EmprCod { get; set; }
        public string AlmaDescrip { get; set; }
        public string AlmaDirec { get; set; }
        public Nullable<short> ComuCodigo { get; set; }
        public string AlmaFono { get; set; }
        public string AlmaFax { get; set; }
        public string AlmaMail { get; set; }
        public string AlmaCCodigo { get; set; }
        public string CtaCFaltaInv { get; set; }
        public Nullable<short> EmplCodigoEncAlma { get; set; }
        public Nullable<double> AlmaCapaMt2 { get; set; }
        public Nullable<double> AlmaCapaUni { get; set; }
        public Nullable<double> AlmaCapaCri { get; set; }
        public Nullable<double> AlmaCoorX { get; set; }
        public Nullable<double> AlmaCoorY { get; set; }
        public string AlmaMapa { get; set; }
        public Nullable<short> AlmaNumero { get; set; }
    }
}
