//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anotacione
    {
        public string EdifCod { get; set; }
        public string TorrCodigo { get; set; }
        public string InmuCodigo { get; set; }
        public double AnotCorrel { get; set; }
        public Nullable<System.DateTime> AnotFecha { get; set; }
        public Nullable<System.DateTime> AnotHora { get; set; }
        public Nullable<short> AnotEstado { get; set; }
        public string AnotDetalle { get; set; }
    }
}
