//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturaCaja
    {
        public string EmprCod { get; set; }
        public string UsrsCodigo { get; set; }
        public short PtosvCodigo { get; set; }
        public double ApeCodigo { get; set; }
        public short ApeAno { get; set; }
        public Nullable<short> TurCodigo { get; set; }
        public Nullable<System.DateTime> ApeHora { get; set; }
        public Nullable<short> ApeAbierta { get; set; }
        public Nullable<double> Ape1 { get; set; }
        public Nullable<double> Ape5 { get; set; }
        public Nullable<double> Ape10 { get; set; }
        public Nullable<double> Ape50 { get; set; }
        public Nullable<double> Ape100 { get; set; }
        public Nullable<double> Ape500 { get; set; }
        public Nullable<double> Ape1000 { get; set; }
        public Nullable<int> Ape2000 { get; set; }
        public Nullable<int> Ape5000 { get; set; }
        public Nullable<double> Ape10000 { get; set; }
        public Nullable<double> Ape20000 { get; set; }
    }
}
