//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AporteRetiro
    {
        public string EmprCod { get; set; }
        public string UsrsCodigo { get; set; }
        public short PtosvCodigo { get; set; }
        public double ApeCodigo { get; set; }
        public short ApeAno { get; set; }
        public Nullable<short> TurCodigo { get; set; }
        public string SupCodigo { get; set; }
        public System.DateTime ARHora { get; set; }
        public Nullable<short> ARTransacc { get; set; }
        public Nullable<double> AR1 { get; set; }
        public Nullable<double> AR5 { get; set; }
        public Nullable<double> AR10 { get; set; }
        public Nullable<double> AR50 { get; set; }
        public Nullable<double> AR100 { get; set; }
        public Nullable<double> AR500 { get; set; }
        public Nullable<double> AR1000 { get; set; }
        public Nullable<int> AR2000 { get; set; }
        public Nullable<int> AR5000 { get; set; }
        public Nullable<double> AR10000 { get; set; }
        public Nullable<double> AR20000 { get; set; }
        public Nullable<double> ARCheques { get; set; }
        public Nullable<double> ARTarDebito { get; set; }
        public Nullable<double> ARTarCredito { get; set; }
        public string ApeGlosa { get; set; }
    }
}
