//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmadoKitProd
    {
        public string KitsCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public string PbarCodigo { get; set; }
        public string EmprCod { get; set; }
        public short KitPCorrel { get; set; }
        public short KitPAno { get; set; }
        public string ArmaSerie { get; set; }
        public string ArmPSerie { get; set; }
        public Nullable<int> ArmPCorrel { get; set; }
    }
}
