//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsiHabSemanaCorrida
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short Ano { get; set; }
        public short Mes { get; set; }
        public int MovMenCorrel { get; set; }
        public int SemanaCorrel { get; set; }
        public Nullable<int> Ausentes { get; set; }
        public Nullable<int> Licencia { get; set; }
        public Nullable<int> Trabajados { get; set; }
        public string HrsNormales { get; set; }
        public string Hrsnocturnas { get; set; }
        public string HrsFestivas { get; set; }
        public string HrsDescuento { get; set; }
        public Nullable<double> OBonos { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Promedio { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> Festivos { get; set; }
    }
}
