//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsoEmpresa
    {
        public string EmprCod { get; set; }
        public int AsoEmpAno { get; set; }
        public int AsoEmpMes { get; set; }
        public string AsoEmpMutual { get; set; }
        public string AsoEmpcaja { get; set; }
        public Nullable<double> AsoEmpCotizacion { get; set; }
    }
}
