//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributosAdicionale
    {
        public string EmprCod { get; set; }
        public string AtadCodigo { get; set; }
        public short TiAtCodigo { get; set; }
        public string AtadDescripcion { get; set; }
        public Nullable<int> AtadTipoDato { get; set; }
        public string AtadSQL1 { get; set; }
        public string AtadSQL2 { get; set; }
        public string CataNomTabla { get; set; }
        public string AtadValDefecto { get; set; }
        public Nullable<short> AtadInstacias { get; set; }
        public Nullable<short> AtadAutomatico { get; set; }
        public string AtadBaseSQL1 { get; set; }
        public string AtadBaseSQL2 { get; set; }
        public string AtadNomControlSugiere1 { get; set; }
        public Nullable<int> AtadColControlSugiere1 { get; set; }
        public Nullable<int> AtadOrden { get; set; }
    }
}
