//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributosEtapa
    {
        public string EmprCod { get; set; }
        public string AtadCodigo { get; set; }
        public string TiflCodigo { get; set; }
        public string EtapCodigo { get; set; }
        public Nullable<int> AtEtPosicionX { get; set; }
        public Nullable<int> AtEtPosicionY { get; set; }
        public Nullable<int> AtEtLargoCampo { get; set; }
        public Nullable<int> AtEtAltoCampo { get; set; }
        public string GrAECodigo { get; set; }
        public Nullable<short> AtEtUnitario { get; set; }
        public Nullable<int> AtEtColumna { get; set; }
        public string AtEtTipoObjeto { get; set; }
        public Nullable<int> AtEtIndiceObjeto { get; set; }
        public Nullable<int> AtEtAnchoColumna { get; set; }
        public Nullable<short> AtEtLocked { get; set; }
        public string AtEtDescripcion { get; set; }
    }
}
