//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoleImpto
    {
        public string EmprCod { get; set; }
        public short BoleAno { get; set; }
        public string BoleTipo { get; set; }
        public double BoleNumero { get; set; }
        public string BoleMTE { get; set; }
        public string ImpuCodigo { get; set; }
        public short RelcExtranjero { get; set; }
        public string SucuCodigo { get; set; }
        public string RelcRut { get; set; }
        public Nullable<double> BimpMonto { get; set; }
        public Nullable<short> BimpMes { get; set; }
        public Nullable<double> BimpBaseImp { get; set; }
        public Nullable<double> BimpTasa { get; set; }
    }
}
