//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        public string SucuCodigo { get; set; }
        public string RelcRut { get; set; }
        public double BoleNumero { get; set; }
        public short RelcExtranjero { get; set; }
        public short BoleAno { get; set; }
        public string BoleTipo { get; set; }
        public string BoleMTE { get; set; }
        public string EmprCod { get; set; }
        public string ListCodigo { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<System.DateTime> BoleFechaPago { get; set; }
        public Nullable<double> BoleSaldo { get; set; }
        public Nullable<short> BoleCuotas { get; set; }
        public Nullable<short> BoleNula { get; set; }
        public string BoleGlosa { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<short> SuccCodigo { get; set; }
        public Nullable<short> ContCodigo { get; set; }
        public Nullable<short> BoleMes { get; set; }
        public Nullable<short> BoleExenta { get; set; }
        public string BoleDesglose { get; set; }
        public Nullable<double> BoleTerreno { get; set; }
        public string UsrsCodigo { get; set; }
        public Nullable<short> PtovCodigo { get; set; }
        public Nullable<double> ApeCodigo { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> BoleTipmMonto { get; set; }
        public Nullable<System.DateTime> BoleFechaIngreso { get; set; }
        public Nullable<double> BoleAfecto { get; set; }
        public Nullable<double> BoleExento { get; set; }
        public Nullable<double> BoleSubTotal { get; set; }
        public Nullable<double> BoleTotal { get; set; }
        public Nullable<short> BolePagada { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<double> BoleVuelto { get; set; }
        public Nullable<System.DateTime> BoleFechaHora { get; set; }
        public Nullable<double> BoleNumeroImpre { get; set; }
        public Nullable<double> BoleNroFiscal { get; set; }
    }
}
