//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoleRecDe
    {
        public string EmprCod { get; set; }
        public short BoleAno { get; set; }
        public string SucuCodigo { get; set; }
        public double BoleNumero { get; set; }
        public short RelcExtranjero { get; set; }
        public string BoleMTE { get; set; }
        public string RelcRut { get; set; }
        public string RecdCodigo { get; set; }
        public string BoleTipo { get; set; }
        public Nullable<double> BrdeNeto { get; set; }
        public Nullable<int> BrdeSingular { get; set; }
        public Nullable<short> BrdeMes { get; set; }
        public Nullable<double> BrdeImpto { get; set; }
        public string BrdeCampoAux { get; set; }
        public Nullable<double> BrdeMonto { get; set; }
        public Nullable<System.DateTime> BrdeFecha { get; set; }
        public Nullable<short> BrdePor { get; set; }
        public Nullable<double> BrdeTasa { get; set; }
        public Nullable<double> BtdeNeto { get; set; }
        public Nullable<int> BrdSingular { get; set; }
        public string BrdCampoAux { get; set; }
        public string BrdFecha { get; set; }
    }
}
