//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoleSesione
    {
        public string EmprCod { get; set; }
        public short BoleAno { get; set; }
        public string BoleTipo { get; set; }
        public double BoleNumero { get; set; }
        public string SucuCodigo { get; set; }
        public double BLinCorrelativo { get; set; }
        public short RelcExtranjero { get; set; }
        public string RelcRut { get; set; }
        public string BoleMTE { get; set; }
        public double BLinCorrelSesion { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<System.DateTime> BlinFechaCreacion { get; set; }
        public Nullable<System.DateTime> BlinFechaSesion { get; set; }
        public Nullable<short> Blinsesrealizada { get; set; }
    }
}
