//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoleCuota
    {
        public string EmprCod { get; set; }
        public short BoleAno { get; set; }
        public string SucuCodigo { get; set; }
        public string BoleTipo { get; set; }
        public string BoleMTE { get; set; }
        public int BcuoCorrelCuota { get; set; }
        public string RelcRut { get; set; }
        public double BoleNumero { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<short> BocuMes { get; set; }
        public Nullable<short> BoCuEstado { get; set; }
        public Nullable<System.DateTime> BoCuVencCuota { get; set; }
        public Nullable<System.DateTime> BoCuFechaTrans { get; set; }
        public Nullable<double> BOCuSaldoCuota { get; set; }
        public Nullable<double> BoCuMontoCuota { get; set; }
    }
}
