//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamposRepImp
    {
        public string TdocCodigo { get; set; }
        public string ImprNombre { get; set; }
        public string RedoArchivo { get; set; }
        public int cariSection { get; set; }
        public int cariItemIndex { get; set; }
        public string cariItemNombre { get; set; }
        public Nullable<int> cariItemLeftPos { get; set; }
        public Nullable<int> cariItemTopPos { get; set; }
        public Nullable<short> cariItemBold { get; set; }
        public Nullable<int> cariItemFontSize { get; set; }
        public Nullable<short> cariItemItalic { get; set; }
        public Nullable<short> cariItemVisible { get; set; }
    }
}
