//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargasFamiliaresCCHC
    {
        public string EmprCod { get; set; }
        public short EmplCodigo { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public string CarFaCCHCRut { get; set; }
        public short CarFaCCHCExt { get; set; }
        public int CarFaCCHCCorrel { get; set; }
        public Nullable<System.DateTime> CarFaCCHCFechaNac { get; set; }
        public Nullable<System.DateTime> CarFaCCHCFechaVenc { get; set; }
        public Nullable<short> CarFaCCHCTipo { get; set; }
        public string CarfaCCHCNombre { get; set; }
    }
}
