//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargasFamiliare
    {
        public string EmprCod { get; set; }
        public short EmplCodigo { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public string CarFaRut { get; set; }
        public short CarFaExt { get; set; }
        public int CarFaCorrel { get; set; }
        public Nullable<System.DateTime> CarFaFechaNac { get; set; }
        public Nullable<System.DateTime> CarFaFechaVenc { get; set; }
        public Nullable<short> CarFaTipo { get; set; }
        public string CarfaNombre { get; set; }
        public Nullable<short> EsCarFaCCHC { get; set; }
    }
}
