//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartolasBancaria
    {
        public string EmprCod { get; set; }
        public string InstCodigo { get; set; }
        public string IfemNumeroCuenta { get; set; }
        public int CabaNumero { get; set; }
        public Nullable<System.DateTime> CabaFecha { get; set; }
        public Nullable<double> CabaSaldoCartola { get; set; }
        public Nullable<double> CabaSaldoCuentaBancaria { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CocoTipmMonto { get; set; }
        public string CtaCCodigo { get; set; }
    }
}
