//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTabla
    {
        public string CataNomTabla { get; set; }
        public string CataLlave1 { get; set; }
        public string CataLlave2 { get; set; }
        public string CataLlave3 { get; set; }
        public string CataLlave4 { get; set; }
        public string CataLlave5 { get; set; }
        public string CataLlave6 { get; set; }
        public string CataLlave7 { get; set; }
        public string CataLlave8 { get; set; }
        public string CataLlave9 { get; set; }
        public string CataLlave10 { get; set; }
        public string CataTDLlave1 { get; set; }
        public string CataTDLlave2 { get; set; }
        public string CataTDLlave3 { get; set; }
        public string CataTDLlave4 { get; set; }
        public string CataTDLlave5 { get; set; }
        public string CataTDLlave6 { get; set; }
        public string CataTDLlave7 { get; set; }
        public string CataTDLlave8 { get; set; }
        public string CataTDLlave9 { get; set; }
        public string CataTDLlave10 { get; set; }
    }
}
