//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenTBoleta
    {
        public string SucuCodigo { get; set; }
        public string RelcRut { get; set; }
        public double CenTNumero { get; set; }
        public short RelcExtranjero { get; set; }
        public short CenTAno { get; set; }
        public string CenTTipo { get; set; }
        public string CenTMTE { get; set; }
        public string EmprCod { get; set; }
        public double CenTNro { get; set; }
        public double CenTLinCorrelativo { get; set; }
        public Nullable<int> CentrTipo { get; set; }
        public Nullable<int> CentSistema { get; set; }
        public Nullable<double> NroVoucher { get; set; }
    }
}
