//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenTPago
    {
        public string SucuCodigo { get; set; }
        public short RelcExtranjero { get; set; }
        public short DcuoCorrel { get; set; }
        public short DpagCorrel { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public string RelcRut { get; set; }
        public short CenTMovimiento { get; set; }
        public double CenTNro { get; set; }
        public double CenTlinCorrel { get; set; }
        public Nullable<short> CentTipo { get; set; }
        public Nullable<int> CentSistema { get; set; }
        public Nullable<double> NroVoucher { get; set; }
        public string EmprCod { get; set; }
    }
}
