//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreCaja
    {
        public string EmprCod { get; set; }
        public string UsrsCodigo { get; set; }
        public short PtosvCodigo { get; set; }
        public double ApeCodigo { get; set; }
        public short ApeAno { get; set; }
        public Nullable<short> TurCodigo { get; set; }
        public Nullable<System.DateTime> CieHora { get; set; }
        public Nullable<short> CieCerrada { get; set; }
        public Nullable<double> Cie1 { get; set; }
        public Nullable<double> Cie5 { get; set; }
        public Nullable<double> Cie10 { get; set; }
        public Nullable<double> Cie50 { get; set; }
        public Nullable<double> Cie100 { get; set; }
        public Nullable<double> Cie500 { get; set; }
        public Nullable<double> Cie1000 { get; set; }
        public Nullable<int> Cie2000 { get; set; }
        public Nullable<int> Cie5000 { get; set; }
        public Nullable<double> Cie10000 { get; set; }
        public Nullable<double> Cie20000 { get; set; }
        public Nullable<double> CieCheques { get; set; }
        public Nullable<double> CieTarDebito { get; set; }
        public Nullable<double> CieTarCredito { get; set; }
        public Nullable<short> CieCuadrada { get; set; }
        public Nullable<double> CieCheqRest { get; set; }
    }
}
