//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocoLinea
    {
        public string EmprCod { get; set; }
        public int CocoAno { get; set; }
        public int CocoMes { get; set; }
        public int CocoNumero { get; set; }
        public int ColiItem { get; set; }
        public string SucuCodigo { get; set; }
        public string CodRCodigo { get; set; }
        public string ColiGlosa { get; set; }
        public string CtaCDebe { get; set; }
        public string CtaCHaber { get; set; }
        public Nullable<double> ColiMtoDebe { get; set; }
        public Nullable<double> ColiMtoHaber { get; set; }
        public Nullable<double> ColiMtoNeto { get; set; }
        public Nullable<double> ColiMtoDebeMonOri { get; set; }
        public Nullable<double> ColiMtoHaberMonOri { get; set; }
        public Nullable<double> ColiMtoNetoMonOri { get; set; }
        public Nullable<short> ColiEsGastoRechazado { get; set; }
        public Nullable<short> ColiEsGastoProvisionado { get; set; }
        public Nullable<short> ColiEsRentaExenta { get; set; }
        public Nullable<short> ColiEsIngresoNoRenta { get; set; }
        public Nullable<short> ColiEsActivoFijo { get; set; }
        public Nullable<int> ColiTipoAnalisis { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<short> DoctMovimiento { get; set; }
        public Nullable<double> DoctNumero { get; set; }
        public Nullable<System.DateTime> DoctFecha { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<short> ColiEsSistema { get; set; }
        public Nullable<System.DateTime> ColiFechaPresupuesto { get; set; }
        public string TipeCodigo { get; set; }
        public string PresCodigo { get; set; }
        public string ItprCodigo { get; set; }
        public Nullable<short> CocoDescuadrado { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CocoTipmMonto { get; set; }
        public Nullable<short> CheqSolicitado { get; set; }
        public Nullable<short> ColiTributario { get; set; }
        public Nullable<System.DateTime> CodoFechaVenc { get; set; }
        public Nullable<short> CodoEsFactura { get; set; }
        public Nullable<short> colisaldado { get; set; }
        public string CodRCodigo_old { get; set; }
    }
}
