//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocoSeguimiento
    {
        public string EmprCod { get; set; }
        public int CocoAno { get; set; }
        public int CocoMes { get; set; }
        public int CocoNumero { get; set; }
        public int CoseItem { get; set; }
        public string UsrsCodigo { get; set; }
        public string CoseGlosa { get; set; }
    }
}
