//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodoImpuesto
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public double DoctNumeroInterno { get; set; }
        public string ImpuCodigo { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<double> CoImMonto { get; set; }
        public Nullable<double> CoImMontoOrig { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CoImTipmMonto { get; set; }
        public Nullable<double> ImpuTasa { get; set; }
    }
}
