//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodoLinea
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public double DoctNumeroInterno { get; set; }
        public double CoitItem { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<double> CoitMonto { get; set; }
        public string CoitGlosa { get; set; }
        public string CodRCodigo { get; set; }
        public Nullable<short> CodoActFijo { get; set; }
        public Nullable<double> CoitMontoOrig { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CoitTipmMonto { get; set; }
        public Nullable<double> CodoNumero { get; set; }
        public string CodoRelcRut { get; set; }
        public Nullable<short> CodoRelcExtranjero { get; set; }
        public Nullable<System.DateTime> CodoFechaAnalisis { get; set; }
        public Nullable<System.DateTime> CodoFechaVencAnalisis { get; set; }
        public string CodoTdocCodigo { get; set; }
        public Nullable<System.DateTime> ColiFechaPresupuesto { get; set; }
        public string TipeCodigo { get; set; }
        public string PresCodigo { get; set; }
        public string ItprCodigo { get; set; }
    }
}
