//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodoAsociado
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public double DoctNumeroInterno { get; set; }
        public string SucuCodigoRel { get; set; }
        public string TdocCodigoRel { get; set; }
        public double DoctNumeroRel { get; set; }
        public double DoctNumeroInternoRel { get; set; }
        public string CoasTipo { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<double> CoAsMonto { get; set; }
    }
}
