//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaImpre
    {
        public string ColCodigo { get; set; }
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string ColNombre { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<double> ColInicio { get; set; }
        public Nullable<double> ColActual { get; set; }
        public Nullable<double> ColFinal { get; set; }
        public Nullable<short> ColMaxLinea { get; set; }
        public string ColRuta { get; set; }
        public string ColArchivo { get; set; }
    }
}
