//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComaLinea
    {
        public string EmprCod { get; set; }
        public int comaNumero { get; set; }
        public int coliCorrelativo { get; set; }
        public Nullable<int> ProdAno { get; set; }
        public string ProdCodigo { get; set; }
        public Nullable<int> coliCantidad { get; set; }
        public Nullable<double> coliPrecioUnitario { get; set; }
        public Nullable<double> coliMontoLinea { get; set; }
        public Nullable<double> coliSaldoLinea { get; set; }
        public Nullable<short> EsKit { get; set; }
        public Nullable<double> ColiNulos { get; set; }
        public string colicomentario { get; set; }
    }
}
