//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComiEmpleado
    {
        public string EmprCod { get; set; }
        public string tacoCodigo { get; set; }
        public Nullable<int> emplCodigo { get; set; }
        public string emplRUTF { get; set; }
        public short emplExtranjero { get; set; }
        public Nullable<double> Comivalor { get; set; }
        public Nullable<short> ComiEsServicio { get; set; }
    }
}
