//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public string EdifCod { get; set; }
        public double CompNumero { get; set; }
        public short CompMovimiento { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string TdocCodigo { get; set; }
        public string SucuCodigo { get; set; }
        public Nullable<short> CompAno { get; set; }
        public Nullable<short> CompMes { get; set; }
        public short CompTipo { get; set; }
        public Nullable<System.DateTime> CompFecha { get; set; }
        public string CompObservaciones { get; set; }
        public Nullable<double> CompNumCuota { get; set; }
        public Nullable<short> CompCorrel { get; set; }
        public string CompDescFormaPago { get; set; }
        public string CtaCCodigo { get; set; }
        public string SistemaOrigen { get; set; }
    }
}
