//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompIELinea
    {
        public string EmprCod { get; set; }
        public double CoIECodigo { get; set; }
        public short CoIETipo { get; set; }
        public double CIELCorrel { get; set; }
        public Nullable<double> CIELTotal { get; set; }
        public string ConCCodigo { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<double> CIELCantidad { get; set; }
        public string CIELObservacion { get; set; }
    }
}
