//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptos_Comex
    {
        public int ID { get; set; }
        public string EmprCod { get; set; }
        public Nullable<short> Ano { get; set; }
        public Nullable<short> Mes { get; set; }
        public string LineaProducto { get; set; }
        public string Concepto { get; set; }
        public string Maestro1 { get; set; }
        public string ACEITE { get; set; }
        public string MAYONESA { get; set; }
        public string CAFE { get; set; }
        public string PASTAS_URUGUAY { get; set; }
        public string PASTAS_ARGENTINA { get; set; }
        public string VINOS_ESPECIALES { get; set; }
        public string CERVEZA { get; set; }
        public string ENERGETICA { get; set; }
        public string PASTAS_PERU { get; set; }
        public string GOURMET { get; set; }
        public string CONSERVAS { get; set; }
        public string MUESTRAS { get; set; }
        public string CAJAS_CARTON { get; set; }
    }
}
