//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public string EdifCod { get; set; }
        public short ConcTipo { get; set; }
        public string ConcCodDependencia { get; set; }
        public string ConcCodigo { get; set; }
        public string ConcNombre { get; set; }
        public Nullable<short> ConcMovDinero { get; set; }
        public Nullable<short> ConcProAuto { get; set; }
        public Nullable<short> ConcProyeccion { get; set; }
        public Nullable<short> ConcTipoMonto { get; set; }
        public Nullable<double> ConcMonto { get; set; }
        public Nullable<short> ConcTipoIngreso { get; set; }
        public Nullable<int> ConcNumFactor { get; set; }
        public string ConcCategoria { get; set; }
        public string ConcSubCategoria { get; set; }
        public string CtaCCodigo { get; set; }
        public string MediCodigo { get; set; }
        public Nullable<short> ConCEsmedicion { get; set; }
        public string ConCDescripcion { get; set; }
        public Nullable<short> ConcGeneraCuota { get; set; }
    }
}
