//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public string EmprCod { get; set; }
        public short ConfAno { get; set; }
        public string SucuCodigo { get; set; }
        public string ConfCtaCExist { get; set; }
        public Nullable<short> ConfEvalStock { get; set; }
        public Nullable<short> ConfCompra { get; set; }
        public Nullable<short> ConfVende { get; set; }
        public string ConfCtaCClientes { get; set; }
        public string ConfCtaCProv { get; set; }
        public Nullable<short> ConfEvalStockCom { get; set; }
        public string ConfCtaCBolNoNom { get; set; }
        public string ConfCtaCBolNom { get; set; }
        public string ConfCtaCV { get; set; }
        public string ConfCtaCCVenta { get; set; }
        public string ConfCtaCCMPerdida { get; set; }
        public string ConfCtaCCMGanancia { get; set; }
    }
}
