//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigCierreAno
    {
        public string CAnoSistema { get; set; }
        public string CAnoNomTabla { get; set; }
        public string CAnoNombreBD { get; set; }
        public Nullable<short> CAnoUsaEmpresa { get; set; }
        public Nullable<short> CAnoCambiaAno { get; set; }
        public string CAnoNombreCampo { get; set; }
        public Nullable<short> CAnoNoTraspasar { get; set; }
        public Nullable<short> CAnoNoTraspasaSqlS { get; set; }
    }
}
