//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confImpreFiscal
    {
        public int ConfImTipo { get; set; }
        public int ConfImCorrel { get; set; }
        public string ConImDescrip { get; set; }
        public Nullable<short> ConImPrecio { get; set; }
    }
}
