//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigGeneral
    {
        public string EmprCod { get; set; }
        public string ConfCtaCliente { get; set; }
        public string ConfCtaProveedor { get; set; }
        public string ConfTDVenta { get; set; }
        public string ConfTDCompra { get; set; }
    }
}
