//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cono
    {
        public int conoNumero { get; set; }
        public int coloCodigo { get; set; }
        public Nullable<short> conoOcupado { get; set; }
        public string conoNombre { get; set; }
    }
}
