//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaDocto
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public double DoctNumeroInterno { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<System.DateTime> CodoFecha { get; set; }
        public string CtaCCodigo { get; set; }
        public string CodRCodigo { get; set; }
        public Nullable<double> CodoMontoAfecto { get; set; }
        public Nullable<double> CodoMontoExento { get; set; }
        public Nullable<double> CodoMonto { get; set; }
        public string CodoGlosa { get; set; }
        public Nullable<short> CodoNulo { get; set; }
        public Nullable<System.DateTime> CodoFechaVenc { get; set; }
        public Nullable<short> CodoMes { get; set; }
        public Nullable<double> CodoTerreno { get; set; }
        public Nullable<short> CodoAno { get; set; }
        public Nullable<double> CodoMontoAfectoOrig { get; set; }
        public string CodoMontoExentoOrig { get; set; }
        public string CodoMontoOrig { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CodoTipmMonto { get; set; }
        public string TipmCodigoCta { get; set; }
        public Nullable<double> CodoMontoAgenAdu { get; set; }
        public Nullable<short> CodoFactElect { get; set; }
    }
}
