//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copropietario
    {
        public string EdifCod { get; set; }
        public string CoprRut { get; set; }
        public short CoprExtranjero { get; set; }
        public short CoprTipo { get; set; }
    }
}
