//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreosEnvio
    {
        public double PaqeCorrel { get; set; }
        public double EnviCorrel { get; set; }
        public short CoEnCorrel { get; set; }
        public string Correo { get; set; }
    }
}
