//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoFinanciero
    {
        public int ID { get; set; }
        public Nullable<int> CfAno { get; set; }
        public Nullable<int> CfMes { get; set; }
        public Nullable<double> CfPorcentaje { get; set; }
        public string EmprCod { get; set; }
        public string Moneda { get; set; }
    }
}
