//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaActivo
    {
        public string EmprCod { get; set; }
        public short CtaCAno { get; set; }
        public string CtaCorreccion { get; set; }
        public string CtaDepreciacion { get; set; }
        public string CtaDepAcumulada { get; set; }
    }
}
