//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCont
    {
        public string CtaCCodigo { get; set; }
        public string EmprCod { get; set; }
        public short CtaCAno { get; set; }
        public string CodrCodigo { get; set; }
        public Nullable<short> CtaCTipo { get; set; }
        public string CtaCNombre { get; set; }
        public Nullable<short> CtaCCentroR { get; set; }
        public string CtaCClave { get; set; }
        public Nullable<short> CtaCHabilitada { get; set; }
        public Nullable<short> CtaCImputable { get; set; }
        public string ClaCCodigo { get; set; }
        public string GruCCodigo { get; set; }
        public Nullable<int> CtaCTipoAnalisis { get; set; }
        public Nullable<short> CtaCEsCapital { get; set; }
        public Nullable<short> CtaCEsBanco { get; set; }
        public string InstCodigoPre { get; set; }
        public string TipeCodigo { get; set; }
        public string ItprCodigo { get; set; }
        public Nullable<int> CtaCNivel { get; set; }
        public Nullable<short> CtaCMultimoneda { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CtaCCorrelativo { get; set; }
        public Nullable<short> CtaCDestacado { get; set; }
        public string CtaCCodigoResult { get; set; }
    }
}
