//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPaletizacion
    {
        public int Id { get; set; }
        public Nullable<double> Base_Pallet { get; set; }
        public Nullable<double> Altura_Pallet { get; set; }
        public Nullable<double> Cajas_Pallet { get; set; }
        public Nullable<double> Altura_Cms { get; set; }
        public Nullable<double> Peso { get; set; }
        public string Cod_Producto { get; set; }
        public string Cod_Sucursal { get; set; }
        public string Rut_Cliente { get; set; }
        public Nullable<double> M3 { get; set; }
        public string EmprCod { get; set; }
    }
}
