//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_VISTA_COBRANZA
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string Rut { get; set; }
        public short Extranjero { get; set; }
        public string Nombre { get; set; }
        public Nullable<short> CodVenddedor { get; set; }
        public string NomVendedor { get; set; }
        public string CodTipoDocto { get; set; }
        public string NomTipoDocto { get; set; }
        public double Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> MontoBruto { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> PlazoPago { get; set; }
        public Nullable<System.DateTime> FechaVenc { get; set; }
        public System.DateTime FechaActual { get; set; }
        public Nullable<int> DiasMora { get; set; }
        public string EstadoVencimiento { get; set; }
        public string ClasificacionMora { get; set; }
        public Nullable<double> CreditoMaximo { get; set; }
        public Nullable<double> Cre_Ocupado { get; set; }
        public Nullable<short> DocNulo { get; set; }
        public string Glosa { get; set; }
        public string DoctoOrigen { get; set; }
    }
}
