//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_OP_PENDIENTE_OPERATIVA
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string cod_TipoDocumento { get; set; }
        public double Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<System.DateTime> F_Vencimiento { get; set; }
        public string RUT { get; set; }
        public short Extranjero { get; set; }
        public Nullable<double> Sucursal { get; set; }
        public Nullable<short> CodVendedor { get; set; }
        public string CodigoListP { get; set; }
        public string CodTipoPago { get; set; }
        public Nullable<short> Nulo { get; set; }
        public string OdocOC { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaPreparacion { get; set; }
        public Nullable<int> MES_DESPACHO { get; set; }
        public Nullable<int> AÑO_DESPACHO { get; set; }
        public string OrdenCompraOriginal { get; set; }
        public string Agenda { get; set; }
        public string Desc_TipoMovimiento { get; set; }
        public string Observaciones { get; set; }
        public string Cod_Producto { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> PrecioUnitarioNeto { get; set; }
        public Nullable<double> PrecioNetoTotFinal { get; set; }
        public Nullable<double> PrecioBrutoTotal { get; set; }
        public Nullable<double> cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public string EsParteKit { get; set; }
        public string COMENTARIO_DEVOLUCION { get; set; }
        public Nullable<double> PrecioUnitFinal { get; set; }
        public string Desc_TipoDocumento { get; set; }
        public Nullable<short> CodRegion { get; set; }
        public Nullable<short> CodCiudad { get; set; }
        public Nullable<short> CodComuna { get; set; }
        public string NomSucursal { get; set; }
        public string Nombre_CliProv { get; set; }
        public string Clasificacion { get; set; }
        public string NomVendedor { get; set; }
        public Nullable<short> CodigoKAM { get; set; }
        public Nullable<double> RelcCreMax { get; set; }
        public string NomListP { get; set; }
        public string NomTipoPago { get; set; }
        public Nullable<int> PlazoPago { get; set; }
        public string Nom_Producto { get; set; }
        public string LineaProducto { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public string NroLote { get; set; }
        public string FECHA_ELABORACION { get; set; }
        public string FECHA_VENCIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_AGENDAMIENTO { get; set; }
        public Nullable<int> ANOAG { get; set; }
        public Nullable<System.TimeSpan> HORA_AGENDAMIENTO { get; set; }
        public string nomregion { get; set; }
        public string nomciudad { get; set; }
        public string nomcomuna { get; set; }
        public string CLASIFICACION_DEVOLUCION { get; set; }
        public string RUTAS { get; set; }
        public string ZONA_GEOGRAFICA { get; set; }
        public Nullable<double> UMPEquivalencia { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<int> NroCamion { get; set; }
        public string Anden { get; set; }
        public string Cita_Agend { get; set; }
        public Nullable<int> Cant_Pallet_Agend { get; set; }
        public Nullable<System.TimeSpan> HoraPostura_Agend { get; set; }
        public Nullable<System.TimeSpan> HoraCarga_Agend { get; set; }
        public string Transporte_Agend { get; set; }
        public string Observación_Agend { get; set; }
        public string cmp_const_01 { get; set; }
        public short Tipo_Movimiento { get; set; }
        public string Departamento { get; set; }
        public string DocuAsociado { get; set; }
        public string DirDespacho { get; set; }
        public Nullable<double> Cre_Disponible { get; set; }
        public Nullable<double> CantPendiente { get; set; }
        public Nullable<double> CajasPendientes { get; set; }
        public Nullable<double> VentaPendiente { get; set; }
        public Nullable<double> KilosPendiente { get; set; }
        public string NombreKAM { get; set; }
        public System.DateTime Actualizacion { get; set; }
        public string TieneAgendamiento { get; set; }
        public string TipoAgendamiento { get; set; }
        public string OpPickeada { get; set; }
        public string Coordinador { get; set; }
        public Nullable<int> MesDocumento { get; set; }
        public Nullable<double> Pallets { get; set; }
        public Nullable<double> PesoBruto { get; set; }
        public Nullable<double> MetrosCubicos { get; set; }
        public string PatenteCamion { get; set; }
    }
}
