//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det1Comex
    {
        public int ID_Det1 { get; set; }
        public Nullable<int> ID_CC { get; set; }
        public string EmprCod { get; set; }
        public Nullable<int> ComxNum { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Campo1 { get; set; }
        public Nullable<double> Campo2 { get; set; }
        public Nullable<double> Campo3 { get; set; }
        public Nullable<double> Campo4 { get; set; }
        public Nullable<double> Campo5 { get; set; }
        public Nullable<double> Campo6 { get; set; }
    }
}
