//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det3Comex
    {
        public int ID_FAG { get; set; }
        public Nullable<int> ID_CC { get; set; }
        public string EmprCod { get; set; }
        public Nullable<int> ComxNum { get; set; }
        public Nullable<int> NroFA { get; set; }
        public string Rut { get; set; }
        public string NomProv { get; set; }
        public Nullable<double> Neto { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Bruto { get; set; }
        public string ConceptoDeGastos { get; set; }
    }
}
