//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetPermiso
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short DetPerAno { get; set; }
        public double DetPerCorr { get; set; }
        public short DetPerMes { get; set; }
        public Nullable<short> DetPerOrigen { get; set; }
        public Nullable<System.DateTime> DetPerFechaIni { get; set; }
        public Nullable<System.DateTime> DetPerFechaFin { get; set; }
        public Nullable<double> DetPerTotalDias { get; set; }
        public Nullable<System.DateTime> DetPerHoraIni { get; set; }
        public Nullable<System.DateTime> DetPerHoraFin { get; set; }
        public string DetPerTotalHoras { get; set; }
        public Nullable<short> DetPerGoceSueldo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string DetPerObs { get; set; }
        public Nullable<double> DetPerTotalPermisos { get; set; }
        public Nullable<short> DetPerRemu { get; set; }
        public Nullable<System.DateTime> DetPerRecupera { get; set; }
        public Nullable<System.DateTime> DetPerRecuHoraIni { get; set; }
        public Nullable<System.DateTime> DetPerRecuHoraFin { get; set; }
        public Nullable<System.DateTime> DetPerRecuperaFin { get; set; }
        public Nullable<short> DetPerSinDescuento { get; set; }
    }
}
