//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetPrestamo
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short DetPreAno { get; set; }
        public double EncPreCorr { get; set; }
        public double DetPreCuota { get; set; }
        public Nullable<double> DetPreValCuota { get; set; }
        public Nullable<System.DateTime> DetPreFechaCanc { get; set; }
        public Nullable<short> DetPreCuoCancelada { get; set; }
        public Nullable<short> DetPreRemu { get; set; }
        public Nullable<short> DetPreCobroAno { get; set; }
        public Nullable<short> DetPreCobroMes { get; set; }
        public Nullable<short> DetPreProrroga { get; set; }
    }
}
