//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasVenta
    {
        public string EmprCod { get; set; }
        public string LproCodigo { get; set; }
        public Nullable<int> LimiteMinimo { get; set; }
        public Nullable<int> LimiteNormal { get; set; }
        public Nullable<int> LimiteInvierno { get; set; }
        public Nullable<int> LimiteMaximo { get; set; }
        public Nullable<int> LimiteSeguridad { get; set; }
    }
}
