//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasImpCurso
    {
        public string EmprCod { get; set; }
        public string CurCod { get; set; }
        public double CImpCorr { get; set; }
        public double DICCorr { get; set; }
        public string DICCod { get; set; }
        public Nullable<System.DateTime> DICHoraIni { get; set; }
        public Nullable<System.DateTime> DICHoraFin { get; set; }
    }
}
