//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocActivo
    {
        public string ActFijoCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ActFijoAno { get; set; }
        public double MovActCodigo { get; set; }
        public string DoctoActOrigen { get; set; }
        public string DoctoActLlave1 { get; set; }
        public string DoctoActLlave2 { get; set; }
        public string DoctoActLlave3 { get; set; }
        public string DoctoActLlave4 { get; set; }
        public string DoctoActLlave5 { get; set; }
        public string DoctoActLlave6 { get; set; }
        public string DoctoActLlave7 { get; set; }
        public string DoctoActLlave8 { get; set; }
        public string DoctoActLlave9 { get; set; }
        public string DoctoActLlave10 { get; set; }
    }
}
