//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocCuota
    {
        public string SucuCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public double DoctNumero { get; set; }
        public short DcuoCorrel { get; set; }
        public string TdocCodigo { get; set; }
        public string EmprCod { get; set; }
        public Nullable<System.DateTime> DcuoFechaT { get; set; }
        public Nullable<short> DcuoEstado { get; set; }
        public Nullable<short> DcuoMax { get; set; }
        public Nullable<System.DateTime> DcuoFechaV { get; set; }
        public Nullable<double> DcuoSaldo { get; set; }
        public Nullable<double> DcuoMonto { get; set; }
        public Nullable<short> DcuoAno { get; set; }
        public Nullable<short> DcuoMes { get; set; }
        public string DcuoObs { get; set; }
    }
}
