//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocDatosComex
    {
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public string EmprCod { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public string SucuCodigo { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<System.DateTime> DoctFechaCarga { get; set; }
        public string DoctDiasViaje { get; set; }
        public Nullable<double> DoctNumeroCarga { get; set; }
        public Nullable<System.DateTime> DoctFechaRealCarga { get; set; }
        public string DoctTransporte { get; set; }
        public string DoctNombreChofer { get; set; }
        public string DoctTrac { get; set; }
        public string DoctSemi { get; set; }
        public string DoctProductoCarga { get; set; }
        public string DoctCajasCarga { get; set; }
        public string DoctPallets { get; set; }
        public string DoctProf { get; set; }
        public string DoctDeposito { get; set; }
        public Nullable<System.DateTime> DoctFechaLlegadaAduana { get; set; }
        public string DoctNumGuiaLoguistica { get; set; }
        public Nullable<System.DateTime> DoctHoraLlegadaAduana { get; set; }
        public Nullable<System.DateTime> DoctFechaSalidaAduana { get; set; }
        public Nullable<System.DateTime> DoctHoraSalidaAduana { get; set; }
        public Nullable<System.DateTime> DoctFechaArribo { get; set; }
        public Nullable<System.DateTime> DoctHoraArribo { get; set; }
        public Nullable<System.DateTime> DoctHoraIngresoDescarga { get; set; }
        public Nullable<System.DateTime> DoctFechaDescarga { get; set; }
        public Nullable<System.DateTime> DoctHoraInicioDescarga { get; set; }
        public Nullable<System.DateTime> DoctHoraTerminoDescarga { get; set; }
        public string DoctAnden { get; set; }
        public string DoctOperador { get; set; }
        public Nullable<short> DoctNumeroArribo { get; set; }
        public Nullable<System.DateTime> DoctFechaVencimientoporlote { get; set; }
        public Nullable<short> DoctNumResolucion { get; set; }
        public Nullable<System.DateTime> DoctFechaResolucion { get; set; }
        public byte[] DoctObservacion { get; set; }
        public Nullable<short> DoctFaltaEnUnidad { get; set; }
        public Nullable<short> DoctCajasRotas { get; set; }
        public string DoctTrovattor { get; set; }
    }
}
