//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocLineasExt
    {
        public string EmprCod { get; set; }
        public double DlinCorrel { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string ProdCodigo { get; set; }
        public Nullable<double> DlinExt1 { get; set; }
        public Nullable<double> DlinExt2 { get; set; }
        public Nullable<double> DlinExt3 { get; set; }
        public Nullable<double> DlinExt4 { get; set; }
        public Nullable<double> DlinExt5 { get; set; }
        public Nullable<double> DlinExt6 { get; set; }
        public Nullable<double> DlinExt7 { get; set; }
        public Nullable<double> DlinExt8 { get; set; }
        public Nullable<double> DlinExt9 { get; set; }
    }
}
