//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocLinea
    {
        public string EmprCod { get; set; }
        public double DlinCorrel { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string ProdCodigo { get; set; }
        public string PbarCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<short> DlinAno { get; set; }
        public Nullable<double> DlinCantidad { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<double> DlinPrecioNeto { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<double> DlinDesclin { get; set; }
        public Nullable<double> DlinSubTotlin { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<short> DlinTieRelac { get; set; }
        public Nullable<double> DlinNetoOrig { get; set; }
        public Nullable<short> DlinTipCodigo { get; set; }
        public Nullable<double> DlinFactorC { get; set; }
        public Nullable<double> DlinPrecioFinal { get; set; }
        public Nullable<short> DlinInventario { get; set; }
        public string DlinOtrRelac { get; set; }
        public Nullable<double> DlinOtrRelacN { get; set; }
        public string CtaCCodigo { get; set; }
        public string CodrCodigo { get; set; }
        public string DlinKitCod { get; set; }
        public Nullable<short> DLinKitCorrel { get; set; }
        public Nullable<double> DlinPrecioBruto { get; set; }
        public Nullable<double> DLinSubTotalBruto { get; set; }
        public string UnimCodigo { get; set; }
        public Nullable<double> UMPEquivalencia { get; set; }
        public Nullable<double> DlinPrecioBrutoOriginal { get; set; }
        public string DlinDescTipo { get; set; }
    }
}
