//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMovimiento
    {
        public short DoctMovimiento { get; set; }
        public short RelcExtranjero { get; set; }
        public string EmprCod { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public string RelcRut { get; set; }
        public int DocmMovimiento { get; set; }
        public string SucuCodigo { get; set; }
        public Nullable<System.DateTime> DocmFecha { get; set; }
        public string DocmUsuario { get; set; }
        public string DocmGlosa { get; set; }
        public string TievCodigo { get; set; }
        public string DocmSistema { get; set; }
    }
}
