//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocPagosContab
    {
        public string Emprcod { get; set; }
        public short CocoAno { get; set; }
        public short CoCoMes { get; set; }
        public int CocoNumero { get; set; }
        public string SucuCodigo { get; set; }
        public int DocPagCorrelativo { get; set; }
        public Nullable<double> DocPagMonto { get; set; }
        public string CtaCCodigo { get; set; }
        public string InstCodigo { get; set; }
        public string TpagCodigo { get; set; }
        public string DocPagNumDocto { get; set; }
        public Nullable<System.DateTime> DocPagFechaV { get; set; }
        public string DocPagGlosa { get; set; }
        public string DocPagRut { get; set; }
        public string DocPagTipo { get; set; }
        public Nullable<System.DateTime> DocPagFechaI { get; set; }
        public Nullable<double> DocPagBruto { get; set; }
        public Nullable<double> DocPagSaldo { get; set; }
        public Nullable<int> DocPagMovimiento { get; set; }
        public Nullable<short> DocPagExt { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<double> DoctNumero { get; set; }
        public Nullable<double> DocPagMontoTotal { get; set; }
        public Nullable<double> DocPagCorrel { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
    }
}
