//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocRecDe
    {
        public short DoctMovimiento { get; set; }
        public double DoctNumero { get; set; }
        public string SucuCodigo { get; set; }
        public string EmprCod { get; set; }
        public string RecdCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public int RecdTipo { get; set; }
        public Nullable<short> DrdeAplica { get; set; }
        public Nullable<double> DrdeMonto { get; set; }
        public string DrdCuenta { get; set; }
        public Nullable<short> DrdePor { get; set; }
        public Nullable<short> DrdeAno { get; set; }
        public Nullable<double> DrdeValor { get; set; }
        public string DrdeNomLargo { get; set; }
        public string DrdeObs { get; set; }
        public string CodrCodigo { get; set; }
        public Nullable<double> DrdeValorBruto { get; set; }
        public Nullable<short> DrdeAplicaMonto { get; set; }
    }
}
