//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctImpresion
    {
        public string EmprCod { get; set; }
        public double DlinCorrel { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string DocSSerie { get; set; }
        public string DoctNombre { get; set; }
        public Nullable<System.DateTime> DoctFechaRecep { get; set; }
        public Nullable<System.DateTime> DoctFechaInicio { get; set; }
        public Nullable<System.DateTime> DoctFechaTermino { get; set; }
        public Nullable<short> DoctVenta { get; set; }
    }
}
