//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public short DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public string EmprCod { get; set; }
        public string TdocCodigo { get; set; }
        public double DoctNumero { get; set; }
        public string SucuCodigo { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<System.DateTime> DoctFechaIngreso { get; set; }
        public Nullable<double> DoctTotalNeto { get; set; }
        public Nullable<double> DoctTotalExento { get; set; }
        public Nullable<System.DateTime> DoctFechaVenc { get; set; }
        public string DoctGlosa { get; set; }
        public Nullable<double> DoctCorrelativo { get; set; }
        public Nullable<short> DoctNula { get; set; }
        public Nullable<double> DoctBruto { get; set; }
        public Nullable<short> DoctCuotas { get; set; }
        public Nullable<double> DoctTerreno { get; set; }
        public string CtacCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> DoctSubTotalNeto { get; set; }
        public Nullable<double> DoctSaldo { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<short> ContCodigo { get; set; }
        public Nullable<double> DoctTipmMonto { get; set; }
        public Nullable<double> DoctAfecto { get; set; }
        public string UsrsCodigo { get; set; }
        public Nullable<short> PtovCodigo { get; set; }
        public Nullable<double> ApeCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<double> SuccCodigo { get; set; }
        public Nullable<short> DoctInventario { get; set; }
        public Nullable<short> DoctPagada { get; set; }
        public Nullable<System.DateTime> DoctFechaPago { get; set; }
        public Nullable<double> DoctBaseImp { get; set; }
        public Nullable<short> DoctAno { get; set; }
        public Nullable<short> DoctMes { get; set; }
        public Nullable<double> DoctNumImpre { get; set; }
        public string DoctDesFPago { get; set; }
        public string DoctOC { get; set; }
        public string TpagCodigo { get; set; }
        public Nullable<double> FPCPCorrel { get; set; }
        public Nullable<short> DoctFactElect { get; set; }
        public string OdocNroOC { get; set; }
        public Nullable<System.DateTime> DoctFechaRealEntrega { get; set; }
        public string DoctNroAtencion { get; set; }
        public Nullable<short> DoctAcuseRecibo { get; set; }
        public string DoctMRClasif { get; set; }
        public Nullable<short> DoctAsegurado { get; set; }
    }
}
