//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosProcesado
    {
        public int id { get; set; }
        public string EmprCod { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<double> DoctNumero { get; set; }
        public string Ruta { get; set; }
        public string Archivo { get; set; }
        public Nullable<short> Procesado { get; set; }
    }
}
