//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFTProduccion
    {
        public string EmprCod { get; set; }
        public string TiflCodigo { get; set; }
        public string EtapCodigo { get; set; }
        public string AlmaCodigoOrigen { get; set; }
        public string AlmaCodigoDestino { get; set; }
        public string TicoCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public Nullable<int> TiCoCorrelativo { get; set; }
    }
}
