//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string EmprCod { get; set; }
        public Nullable<int> EmprRut { get; set; }
        public string EmprDigito { get; set; }
        public string EmprNombre { get; set; }
        public string EmprPaterno { get; set; }
        public string EmprMaterno { get; set; }
        public string EmprDireccion { get; set; }
        public string EmprNumDire { get; set; }
        public string EmprOficinaNum { get; set; }
        public string EmprVillaDire { get; set; }
        public Nullable<short> EmprRegion { get; set; }
        public Nullable<short> ComuCodigo { get; set; }
        public Nullable<short> CiudCodigo { get; set; }
        public string EmprDirPos { get; set; }
        public Nullable<short> EmprArea { get; set; }
        public Nullable<int> EmprFono { get; set; }
        public Nullable<int> EmprFax { get; set; }
        public string EmpreMail { get; set; }
        public Nullable<int> EmprCodAct { get; set; }
        public string EmprGiro { get; set; }
        public Nullable<short> EmprConstr { get; set; }
        public Nullable<short> EmpBloqVig { get; set; }
        public string EmprRepLegal { get; set; }
        public Nullable<int> EmprRutRLegal { get; set; }
        public string EmprDigRLegal { get; set; }
        public string EmprPaginaWeb { get; set; }
        public Nullable<double> EmprCoorX { get; set; }
        public Nullable<double> EmprCoorY { get; set; }
        public string EmprMapa { get; set; }
        public Nullable<short> EmprServ { get; set; }
        public Nullable<int> EmprCantEmpl { get; set; }
        public Nullable<short> EmprLey20255 { get; set; }
    }
}
