//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncCpaVta
    {
        public string SucCodEmp { get; set; }
        public Nullable<short> ECVTMov { get; set; }
        public string DocCod { get; set; }
        public Nullable<double> ECVNumDoc { get; set; }
        public string CpRut { get; set; }
        public bool CpExt { get; set; }
        public Nullable<short> ECVAnoCon { get; set; }
        public Nullable<short> ECVMesCon { get; set; }
        public Nullable<System.DateTime> ECVFecha { get; set; }
        public Nullable<double> ECVNeto { get; set; }
        public Nullable<double> ECVExento { get; set; }
        public Nullable<System.DateTime> ECVVence { get; set; }
        public string ECVGlosa { get; set; }
        public Nullable<double> ECVCorrel { get; set; }
        public string SucCod { get; set; }
        public bool ECVNula { get; set; }
        public Nullable<double> ECVTerreno { get; set; }
        public Nullable<short> VenCod { get; set; }
        public string CtaCod { get; set; }
        public Nullable<double> ECVMontoPago { get; set; }
        public Nullable<double> ECVVouPago { get; set; }
        public Nullable<System.DateTime> ECVFechaPI { get; set; }
        public string EmprCod { get; set; }
    }
}
