//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteLinea
    {
        public string EmprCod { get; set; }
        public short EnTeAno { get; set; }
        public int EnTeTipo { get; set; }
        public string EnTeNumero { get; set; }
        public double EnLiNumero { get; set; }
        public string ProdCodigo { get; set; }
        public string DocSSerie { get; set; }
        public Nullable<double> GuReNumero { get; set; }
        public string GuReRut { get; set; }
        public Nullable<short> GuReExtranjero { get; set; }
    }
}
