//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADAS_Y_SALIDAS
    {
        public string Empresa { get; set; }
        public short Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Almacen { get; set; }
        public double Número { get; set; }
        public Nullable<byte> Cod_Tipo { get; set; }
        public string Nom_Tipo { get; set; }
        public string Cod_Producto { get; set; }
        public string Nom_Producto { get; set; }
        public string Cod_Departamento { get; set; }
        public string Nom_Departamento { get; set; }
        public string Cod_Linea_Producto { get; set; }
        public string Nom_Linea_Producto { get; set; }
        public string Cod_Grupo { get; set; }
        public string Nom_Grupo { get; set; }
        public Nullable<short> Cod_Marca { get; set; }
        public string Nom_Marca { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Unitario_Ingrresado { get; set; }
        public Nullable<double> Total__Unitario_Linea { get; set; }
        public Nullable<double> CostoPMP_Unitario { get; set; }
        public Nullable<double> TotalCostoPMP { get; set; }
        public string Cod_Clasificacion { get; set; }
        public string Nom_Clasificacion { get; set; }
        public Nullable<double> Cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public string Empleado { get; set; }
        public string Glosa { get; set; }
    }
}
