//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPagosold
    {
        public string EmprCod { get; set; }
        public double EPNumero { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<int> EPAno { get; set; }
        public Nullable<int> EPMes { get; set; }
        public Nullable<System.DateTime> EPFecha { get; set; }
        public Nullable<int> EmplCodigo { get; set; }
        public Nullable<double> EPAfecto { get; set; }
        public Nullable<double> EPExento { get; set; }
        public Nullable<double> EPSubTotal { get; set; }
        public Nullable<double> EPIVA { get; set; }
        public Nullable<double> EPTotal { get; set; }
        public Nullable<double> EPNumFA { get; set; }
        public Nullable<double> EPNumNC { get; set; }
        public string EPObservacion { get; set; }
        public int EPTipo { get; set; }
        public Nullable<int> SuccCodigo { get; set; }
        public string EPFiltroBodega { get; set; }
        public string EPFiltroLP { get; set; }
    }
}
