//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa
    {
        public int ID { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string ETAPA1 { get; set; }
        public Nullable<int> TIEMPO { get; set; }
        public Nullable<int> AREA { get; set; }
        public Nullable<bool> AUTO { get; set; }
    }
}
