//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalAlterApli
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public string PEEncCod { get; set; }
        public double EVEncCorr { get; set; }
        public double PEItemCorr { get; set; }
        public string PEAlterCod { get; set; }
        public string EVAlterDesc { get; set; }
    }
}
