//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F29II
    {
        public string EmprCod { get; set; }
        public int F29Ano { get; set; }
        public int F29Mes { get; set; }
        public string L000_C015 { get; set; }
        public string L001_C585 { get; set; }
        public string L001_C020 { get; set; }
        public string L002_C586 { get; set; }
        public string L002_C142 { get; set; }
        public string L003_C515 { get; set; }
        public string L003_C587 { get; set; }
        public string L004_C503 { get; set; }
        public string L004_C502 { get; set; }
        public string L005_C110 { get; set; }
        public string L005_C111 { get; set; }
        public string L006_C512 { get; set; }
        public string L006_C513 { get; set; }
        public string L007_C509 { get; set; }
        public string L007_C510 { get; set; }
        public string L008_C516 { get; set; }
        public string L008_C517 { get; set; }
        public string L009_C500 { get; set; }
        public string L009_C501 { get; set; }
        public string L010_C154 { get; set; }
        public string L011_C518 { get; set; }
        public string L012_C538 { get; set; }
        public string L013_C511 { get; set; }
        public string L013_C514 { get; set; }
        public string L014_C564 { get; set; }
        public string L014_C521 { get; set; }
        public string L015_C566 { get; set; }
        public string L015_C560 { get; set; }
        public string L016_C584 { get; set; }
        public string L016_C562 { get; set; }
        public string L017_C519 { get; set; }
        public string L017_C520 { get; set; }
        public string L018_C524 { get; set; }
        public string L018_C525 { get; set; }
        public string L019_C527 { get; set; }
        public string L019_C528 { get; set; }
        public string L020_C531 { get; set; }
        public string L020_C532 { get; set; }
        public string L021_C534 { get; set; }
        public string L021_C535 { get; set; }
        public string L022_C536 { get; set; }
        public string L022_C553 { get; set; }
        public string L023_C504 { get; set; }
        public string L024_C593 { get; set; }
        public string L025_C594 { get; set; }
        public string L026_C592 { get; set; }
        public string L027_C539 { get; set; }
        public string L028_C164 { get; set; }
        public string L029_C127 { get; set; }
        public string L030_C544 { get; set; }
        public string L031_C523 { get; set; }
        public string L032_C537 { get; set; }
        public string L033_C077 { get; set; }
        public string L033_C089 { get; set; }
        public string L034_C050 { get; set; }
        public string L035_C048 { get; set; }
        public string L036_C151 { get; set; }
        public string L037_C153 { get; set; }
        public string L038_C054 { get; set; }
        public string L039_C056 { get; set; }
        public string L040_C588 { get; set; }
        public string L041_C589 { get; set; }
        public string L042_C030 { get; set; }
        public string L042_C563 { get; set; }
        public string L042_C115 { get; set; }
        public string L042_C068 { get; set; }
        public string L042_C062 { get; set; }
        public string L043_C565 { get; set; }
        public string L043_C120 { get; set; }
        public string L043_C542 { get; set; }
        public string L043_C122 { get; set; }
        public string L043_C123 { get; set; }
        public string L044_C152 { get; set; }
        public string L045_C070 { get; set; }
        public string L046_C066 { get; set; }
        public string L047_C595 { get; set; }
        public string L000_C001 { get; set; }
        public string L000_C002 { get; set; }
        public string L000_C005 { get; set; }
        public string L000_C583 { get; set; }
        public string L093_C091 { get; set; }
        public string L094_C092 { get; set; }
        public string L095_C093 { get; set; }
        public string L096_C094 { get; set; }
        public string L048_C529 { get; set; }
        public string L049_C530 { get; set; }
        public string L050_C409 { get; set; }
        public string L051_C522 { get; set; }
        public string L052_C130 { get; set; }
        public string L052_C526 { get; set; }
        public string L053_C113 { get; set; }
        public string L054_C028 { get; set; }
        public string L055_C548 { get; set; }
        public string L056_C540 { get; set; }
        public string L057_C541 { get; set; }
        public string L058_C549 { get; set; }
        public string L058_C550 { get; set; }
        public string L059_C577 { get; set; }
        public string L060_C032 { get; set; }
        public string L061_C150 { get; set; }
        public string L062_C146 { get; set; }
        public string L063_C545 { get; set; }
        public string L064_C546 { get; set; }
        public string L065_C602 { get; set; }
        public string L066_C575 { get; set; }
        public string L066_C576 { get; set; }
        public string L067_C574 { get; set; }
        public string L067_C033 { get; set; }
        public string L068_C580 { get; set; }
        public string L068_C149 { get; set; }
        public string L069_C582 { get; set; }
        public string L069_C085 { get; set; }
        public string L070_C551 { get; set; }
        public string L071_C559 { get; set; }
        public string L072_C508 { get; set; }
        public string L073_C533 { get; set; }
        public string L074_C552 { get; set; }
        public string L075_C603 { get; set; }
        public string L076_C507 { get; set; }
        public string L076_C506 { get; set; }
        public string L077_C556 { get; set; }
        public string L078_C557 { get; set; }
        public string L079_C558 { get; set; }
        public string L080_C543 { get; set; }
        public string L081_C573 { get; set; }
        public string L081_C598 { get; set; }
        public string L082_C039 { get; set; }
        public string L083_C554 { get; set; }
        public string L084_C597 { get; set; }
        public string L085_C555 { get; set; }
        public string L085_C596 { get; set; }
        public string L086_C160 { get; set; }
        public string L086_C161 { get; set; }
        public string L086_C570 { get; set; }
        public string L087_C126 { get; set; }
        public string L087_C128 { get; set; }
        public string L087_C571 { get; set; }
        public string L088_C572 { get; set; }
        public string L088_C568 { get; set; }
        public string L088_C590 { get; set; }
        public string L089_C547 { get; set; }
        public string L090_C073 { get; set; }
        public string L091_C130 { get; set; }
        public string L092_C591 { get; set; }
        public string L000_C006 { get; set; }
        public string L000_C610 { get; set; }
        public string L000_C611 { get; set; }
        public string L000_C612 { get; set; }
        public string L000_C008 { get; set; }
        public string L000_C053 { get; set; }
        public string L000_C613 { get; set; }
        public string L000_C009 { get; set; }
        public string L000_C601 { get; set; }
        public string L000_C604 { get; set; }
        public string L000_C055 { get; set; }
        public string L000_C044 { get; set; }
        public string L000_C726 { get; set; }
        public string L000_C313 { get; set; }
        public string L000_C314 { get; set; }
        public Nullable<double> F29ValorUTM { get; set; }
    }
}
