//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechasCompC
    {
        public string emprcod { get; set; }
        public int cocoano { get; set; }
        public int cocomes { get; set; }
        public int coconumero { get; set; }
        public string sucucodigo { get; set; }
        public Nullable<System.DateTime> cocofecha2 { get; set; }
    }
}
