//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FECHAS_OP_FA_HR
    {
        public Nullable<double> NUmeroOP { get; set; }
        public Nullable<System.DateTime> FechaOP { get; set; }
        public double NumeroFact { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<double> NumeroHR { get; set; }
        public Nullable<System.DateTime> FechaHR { get; set; }
        public Nullable<System.DateTime> FechaDespachoOP { get; set; }
        public string Vendedor { get; set; }
        public string Nombre_CliProv { get; set; }
        public Nullable<double> TOTAL_NETO_LINEA { get; set; }
    }
}
