//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FECHA_DOCUMENTOS_COMPRAS_VENTAS
    {
        public string Empresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Glosa { get; set; }
        public string Usuario { get; set; }
        public double Numero { get; set; }
        public string Rut { get; set; }
        public short Extranjero { get; set; }
        public string Tipo_Docto { get; set; }
        public string Nombre_Cliente { get; set; }
        public Nullable<short> Mes { get; set; }
        public Nullable<short> ANo { get; set; }
        public string Hora_texto { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
    }
}
