//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiniLinea
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short FiniAno { get; set; }
        public short FiniMes { get; set; }
        public int MovMenCorrel { get; set; }
        public short FiniCorrel { get; set; }
        public string FiniConcepto { get; set; }
        public Nullable<double> FiniMonto { get; set; }
    }
}
