//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folio_Alerta
    {
        public int ID { get; set; }
        public string EmprCod { get; set; }
        public string TdocCodigo { get; set; }
        public int cantidad { get; set; }
        public string email { get; set; }
    }
}
