//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaleriaPaquete
    {
        public short GPEmpresa { get; set; }
        public int GPNPaquete { get; set; }
        public string GPNombreTabla { get; set; }
        public string GPNombrePaquete { get; set; }
        public Nullable<short> GPCorrelativo { get; set; }
        public string GpSistema { get; set; }
    }
}
