//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaReLinea
    {
        public int GareLiCorrelativo { get; set; }
        public short GareCorrelativo { get; set; }
        public string GareLiCampo1 { get; set; }
        public string GareLiCampo2 { get; set; }
    }
}
