//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneProEcoTec
    {
        public string EmprCod { get; set; }
        public string ProCodigo { get; set; }
        public short GProOrigen { get; set; }
        public double GProRevision { get; set; }
        public Nullable<short> GProGenerado { get; set; }
        public string GProNomArchivo { get; set; }
    }
}
