//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraficosEnDemanda
    {
        public string GraCodigo { get; set; }
        public string GraNombre { get; set; }
        public string GraTabla { get; set; }
        public string GraCampo0 { get; set; }
        public string GraNombre0 { get; set; }
        public string GraCampo1 { get; set; }
        public string GraNombre1 { get; set; }
        public string GraCampo2 { get; set; }
        public string GraNombre2 { get; set; }
        public string GraCampo3 { get; set; }
        public string GraNombre3 { get; set; }
        public string GraCampo4 { get; set; }
        public string GraNombre4 { get; set; }
        public string GraOrderBy { get; set; }
    }
}
