//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrBoRango
    {
        public string EmprCod { get; set; }
        public double GrBoNumero { get; set; }
        public double GbRaItem { get; set; }
        public Nullable<System.DateTime> GbRaFecha { get; set; }
        public Nullable<double> GbRaDesde { get; set; }
        public Nullable<double> GbRaHasta { get; set; }
        public Nullable<double> GrRaBruto { get; set; }
        public Nullable<double> GrRaNeto { get; set; }
        public Nullable<double> GrRaImpuesto { get; set; }
        public Nullable<double> GrRaExento { get; set; }
    }
}
