//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposProd
    {
        public string GproCodigo { get; set; }
        public string EmprCod { get; set; }
        public string GproNombre { get; set; }
        public string CodrCodigo { get; set; }
        public string ContCtaCodigo { get; set; }
        public string GproGlosa { get; set; }
        public string GproNombreFoto { get; set; }
        public Nullable<short> GproOcultaTS { get; set; }
        public Nullable<int> GproMacroCategoria { get; set; }
    }
}
