//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GureEnteTecnico
    {
        public string GureRut { get; set; }
        public string Emprcod { get; set; }
        public double GureNumero { get; set; }
        public short GureExtranjero { get; set; }
        public string EnTeNumero { get; set; }
        public string EnteRutResponsable { get; set; }
        public short EnteExtResponsable { get; set; }
    }
}
