//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberesDescuento
    {
        public string EmprCod { get; set; }
        public string HDCodigo { get; set; }
        public string HDDEscripcion { get; set; }
        public string HDTipo { get; set; }
        public Nullable<short> HDImponible { get; set; }
        public Nullable<short> HDTributable { get; set; }
        public Nullable<short> HDAdicHorasEx { get; set; }
        public Nullable<short> HDReliquidable { get; set; }
        public Nullable<short> HDAnticipo { get; set; }
        public Nullable<short> HDVariable { get; set; }
        public Nullable<short> HDFijoEnP { get; set; }
        public Nullable<double> HDValorP { get; set; }
        public Nullable<short> HDFijoOtMoneda { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> HDMontoMoneda { get; set; }
        public Nullable<int> HDDia { get; set; }
        public Nullable<short> HDEsPorcentaje { get; set; }
        public Nullable<double> HDValorPorcentaje { get; set; }
        public Nullable<short> HDSueldoBase { get; set; }
        public Nullable<short> HDSBdiario { get; set; }
        public Nullable<short> HDServiciosMedicos { get; set; }
        public Nullable<short> HDSobreSBP { get; set; }
        public Nullable<short> HDSobreSBG { get; set; }
        public Nullable<short> HDSobreTotalG { get; set; }
        public Nullable<short> HDSobreOB { get; set; }
        public Nullable<short> HDEsSemanaCorrida { get; set; }
        public Nullable<short> HDSobreSImponible { get; set; }
        public Nullable<short> HDVAROtMoneda { get; set; }
        public string TipmCodigoVAR { get; set; }
        public Nullable<double> HDMontoMonedaVAR { get; set; }
        public Nullable<int> HDDiaVAR { get; set; }
        public Nullable<short> HDServDentalCCHC { get; set; }
        public Nullable<short> HDTraspasaMES { get; set; }
        public Nullable<short> HDPropDiasTrab { get; set; }
        public Nullable<short> HDSobreHHN { get; set; }
        public Nullable<short> HDSCorrida20281 { get; set; }
        public Nullable<short> HDSBaseSCorrida20281 { get; set; }
        public Nullable<short> HDConsideraFiniquito { get; set; }
    }
}
