//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABERES_DESCUENTOS_TALANA
    {
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Imponible { get; set; }
        public string Tributable { get; set; }
        public string Formula { get; set; }
        public string Cuenta_Contable { get; set; }
        public string NombreCuenta { get; set; }
        public string Recurrente { get; set; }
        public string ConsideraFiniquito { get; set; }
        public string INE { get; set; }
        public string Comentarios { get; set; }
        public string Proporciona_dias_trabajados { get; set; }
    }
}
