//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoConta
    {
        public Nullable<int> Per { get; set; }
        public string DocCod { get; set; }
        public Nullable<double> ECVNumDoc { get; set; }
        public string CpRut { get; set; }
        public bool CpExt { get; set; }
        public string CpNom { get; set; }
        public string CtaCod { get; set; }
        public Nullable<double> DCVMonto { get; set; }
        public string DCVGlosa { get; set; }
        public Nullable<int> DVouCorr { get; set; }
        public Nullable<System.DateTime> ECVFecha { get; set; }
        public Nullable<System.DateTime> ECVVence { get; set; }
        public string DocCodPago { get; set; }
        public Nullable<double> NumMov { get; set; }
        public Nullable<short> TipoMov { get; set; }
    }
}
