//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short HistAno { get; set; }
        public short HistMes { get; set; }
        public Nullable<double> HistCertificado { get; set; }
        public Nullable<double> HistSueldoImponible { get; set; }
        public Nullable<double> HistSueldoTributable { get; set; }
        public Nullable<double> HistMontoAFP { get; set; }
        public Nullable<double> HistMontoIsapre { get; set; }
        public Nullable<double> HistBaseTributable { get; set; }
        public Nullable<double> HistImptoUnico { get; set; }
        public Nullable<double> HistMayorRetencion { get; set; }
        public Nullable<double> HistGratificacion { get; set; }
        public Nullable<double> HistTasaAFP { get; set; }
        public Nullable<double> HistTasaAFC { get; set; }
        public Nullable<double> HistMontoAFC { get; set; }
        public Nullable<double> HistTotalMontoAPV { get; set; }
        public Nullable<double> HistMontoRentaExenta { get; set; }
        public Nullable<double> HistMontoZonaExtrema { get; set; }
        public Nullable<double> HistMontoNoGravada { get; set; }
    }
}
