//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistUltEstAnalisis20161229
    {
        public string EmprCod { get; set; }
        public Nullable<int> CocoAno { get; set; }
        public Nullable<int> CocoMes { get; set; }
        public Nullable<int> CocoNumero { get; set; }
        public Nullable<int> ColiItem { get; set; }
        public string SucuCodigo { get; set; }
        public string CodRCodigo { get; set; }
        public string ColiGlosa { get; set; }
        public string CtaCDebe { get; set; }
        public string CtaCHaber { get; set; }
        public Nullable<double> ColiMtoDebe { get; set; }
        public Nullable<double> ColiMtoHaber { get; set; }
        public Nullable<double> ColiMtoNeto { get; set; }
        public Nullable<double> ColiMtoDebeMonOri { get; set; }
        public Nullable<double> ColiMtoHaberMonOri { get; set; }
        public Nullable<double> ColiMtoNetoMonOri { get; set; }
        public bool ColiEsGastoRechazado { get; set; }
        public bool ColiEsGastoProvisionado { get; set; }
        public bool ColiEsRentaExenta { get; set; }
        public bool ColiEsIngresoNoRenta { get; set; }
        public bool ColiEsActivoFijo { get; set; }
        public Nullable<int> ColiTipoAnalisis { get; set; }
        public string TdocCodigo { get; set; }
        public short DoctMovimiento { get; set; }
        public double DoctNumero { get; set; }
        public Nullable<System.DateTime> DoctFecha { get; set; }
        public string RelcRut { get; set; }
        public bool RelcExtranjero { get; set; }
        public bool ColiEsSistema { get; set; }
        public Nullable<System.DateTime> ColiFechaPresupuesto { get; set; }
        public string TipeCodigo { get; set; }
        public string PresCodigo { get; set; }
        public string ItprCodigo { get; set; }
        public bool CocoDescuadrado { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> CocoTipmMonto { get; set; }
        public bool CheqSolicitado { get; set; }
        public bool ColiTributario { get; set; }
        public Nullable<System.DateTime> CodoFechaVenc { get; set; }
        public bool CodoEsFactura { get; set; }
        public Nullable<short> colisaldado { get; set; }
    }
}
