//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORAS_EXTRAS
    {
        public string Empresa { get; set; }
        public short Año { get; set; }
        public short Mes { get; set; }
        public string Rut { get; set; }
        public string Apellido_P { get; set; }
        public string Apellido_M { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string CentroCosto { get; set; }
        public Nullable<double> Horas_Extras_Monto { get; set; }
        public Nullable<double> Cant_horas_extras { get; set; }
        public Nullable<double> Minutos_horas_extras { get; set; }
        public Nullable<double> Cant_horas_DESCUENTO { get; set; }
        public Nullable<double> Minutos_horas_DESCUENTO { get; set; }
        public string DEPARTAMENTO { get; set; }
    }
}
