//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoRuLineas_DEL
    {
        public double HoRuNumero { get; set; }
        public string HoRuTdocCodigo { get; set; }
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public double HoruCorrel { get; set; }
        public Nullable<int> HoRuAno { get; set; }
        public Nullable<int> HoRuMes { get; set; }
        public string RelcRutTrans { get; set; }
        public Nullable<short> RelcExtranjeroTrans { get; set; }
        public Nullable<short> SuccCodigoTrans { get; set; }
        public Nullable<double> DoctNumero { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<short> DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<short> SuccCodigo { get; set; }
        public string HRLiRazonSoc { get; set; }
        public string HRLiNomSuc { get; set; }
        public Nullable<short> DoctAno { get; set; }
        public Nullable<short> DoctMes { get; set; }
        public Nullable<double> HRLiKilosDocto { get; set; }
        public Nullable<int> HRLiCodComuDesp { get; set; }
        public string HRLiDirDesp { get; set; }
        public Nullable<short> HRLiEstado { get; set; }
        public Nullable<double> HRLiMontoCancelar { get; set; }
        public Nullable<double> HRLiMontoPagado { get; set; }
        public Nullable<short> HoRuNula { get; set; }
        public Nullable<short> HoRuNODispPago { get; set; }
        public string HoRuTipo { get; set; }
        public string HoruEmprCod { get; set; }
    }
}
