//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMEGA_FA_HOJA_RUTAS
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string Cod_TipoDocumento { get; set; }
        public string Desc_TipoDocumento { get; set; }
        public double Numero_FA { get; set; }
        public string NomCliente { get; set; }
        public string NomSucursalCliente { get; set; }
        public Nullable<System.DateTime> Fecha_FA { get; set; }
        public Nullable<double> Numero_HR { get; set; }
        public Nullable<short> HoRuNula { get; set; }
        public Nullable<short> HRLiEstado { get; set; }
        public Nullable<short> HoRuNODispPago { get; set; }
        public string HoRuTipo { get; set; }
        public Nullable<double> HRLiKilosDocto { get; set; }
        public string NomComunaDesp { get; set; }
        public string HRLiDirDesp { get; set; }
        public Nullable<double> HRLiMontoCancelar { get; set; }
        public Nullable<double> HRLiMontoPagado { get; set; }
    }
}
