//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMEGA_HOJAS_RUTAS
    {
        public string Empresa { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public double HRNumero { get; set; }
        public Nullable<short> HoRuNula { get; set; }
        public Nullable<short> DisponibleParaPago { get; set; }
        public Nullable<short> HRLiEstado { get; set; }
        public Nullable<System.DateTime> HoRuFecha { get; set; }
        public Nullable<double> NumeroDocto { get; set; }
        public Nullable<double> TotalNeto { get; set; }
        public Nullable<double> TotalBruto { get; set; }
        public Nullable<double> PesoDocumento { get; set; }
        public string NomChofer { get; set; }
        public string NomTransportista { get; set; }
        public Nullable<double> HRLiMontoPagado { get; set; }
        public Nullable<int> CodComuna { get; set; }
        public string NomComuna { get; set; }
        public string Patente { get; set; }
        public Nullable<double> CapacidadT { get; set; }
        public string NomCliente { get; set; }
        public Nullable<short> CodSucCliente { get; set; }
        public string NomSucCliente { get; set; }
        public string DirSucCliente { get; set; }
        public Nullable<short> CodCiuSucCliente { get; set; }
        public string NomCiuCliente { get; set; }
        public Nullable<short> CodRegionCliente { get; set; }
        public string NomRegionCliente { get; set; }
        public string Cod_TipoDocumento { get; set; }
        public string Desc_TipoDocumento { get; set; }
        public Nullable<System.DateTime> Fecha_FA { get; set; }
        public string HoRuTipo { get; set; }
        public string HRLiDirDesp { get; set; }
        public Nullable<double> HRLiMontoCancelar { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Chofer_Bloqueado { get; set; }
        public string Patente_Bloqueada { get; set; }
    }
}
