//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpuestoUnico
    {
        public short IUMes { get; set; }
        public short IUAno { get; set; }
        public double IUDesde { get; set; }
        public double IUHasta { get; set; }
        public Nullable<double> IUFactor { get; set; }
        public Nullable<double> IURebaja { get; set; }
    }
}
