//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InicioRapido
    {
        public string IRCodProducto { get; set; }
        public string EmprCod { get; set; }
        public int IRAno { get; set; }
        public string IRNomProducto { get; set; }
        public Nullable<double> IRprecioV { get; set; }
        public Nullable<double> IRStock { get; set; }
        public string IResmodificado { get; set; }
    }
}
