//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructore
    {
        public string EmprCod { get; set; }
        public string InstruCodigo { get; set; }
        public string InstruRut { get; set; }
        public Nullable<short> instruExt { get; set; }
        public string InstruNombre { get; set; }
        public string InstruApellidoP { get; set; }
        public string InstruApellidoM { get; set; }
        public Nullable<short> InstruEsExterno { get; set; }
        public string InstruFono { get; set; }
        public string InstruTituloProf { get; set; }
        public string InstruCargo { get; set; }
        public string InstruPerfil { get; set; }
    }
}
