//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLinea
    {
        public string EmprCod { get; set; }
        public short InveAno { get; set; }
        public short InveMes { get; set; }
        public string AlmaCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public double InveNumero { get; set; }
        public Nullable<double> IlinExedentes { get; set; }
        public Nullable<double> IlinMin { get; set; }
        public Nullable<double> ProdPrecioC { get; set; }
        public Nullable<double> IlinStockTeorico { get; set; }
        public Nullable<double> IlinStockFisico { get; set; }
        public Nullable<double> IlinFaltInv { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<double> IlinDif { get; set; }
        public Nullable<double> IlinMerma { get; set; }
        public Nullable<double> IlinMax { get; set; }
    }
}
