//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSery
    {
        public string ProdCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public string EmprCod { get; set; }
        public short InseAno { get; set; }
        public short InseMes { get; set; }
        public string InseNumSerie { get; set; }
        public Nullable<double> DlinCorrel { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public Nullable<double> DoctNumero { get; set; }
        public Nullable<short> DoctMovimiento { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public string PbarCodigo { get; set; }
        public Nullable<System.DateTime> InseFechaIngreso { get; set; }
        public Nullable<int> InseMesesGarantia { get; set; }
    }
}
