//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsFERCtaCont
    {
        public string EmprCod { get; set; }
        public string foerCodigo { get; set; }
        public string iferCodigo { get; set; }
        public string CtaCCodigo { get; set; }
        public short CtaCAno { get; set; }
        public Nullable<int> itccPosicion { get; set; }
        public Nullable<int> itccSigno { get; set; }
        public string CodrCodigo { get; set; }
    }
}
