//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARDEX
    {
        public string Producto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Movimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public string MueveStock { get; set; }
        public Nullable<double> NumeroDocto { get; set; }
        public Nullable<double> Entrada { get; set; }
        public Nullable<double> Salida { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> Entrada__ { get; set; }
        public Nullable<double> Salida__ { get; set; }
        public Nullable<double> PMP { get; set; }
        public Nullable<double> Saldo__ { get; set; }
        public Nullable<double> Orden { get; set; }
        public string CodTipoDocumento { get; set; }
    }
}
