//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        public string KitsCodigo { get; set; }
        public string EmprCod { get; set; }
        public short KitsAno { get; set; }
        public string KitsDescripcion { get; set; }
        public string KitsBarCodigo { get; set; }
        public string KitsNombreFoto { get; set; }
        public string KitsCtaVtas { get; set; }
        public string GproCodigo { get; set; }
    }
}
