//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitGarzone
    {
        public string Emprcod { get; set; }
        public int KigaCorrel { get; set; }
        public string KigaCod { get; set; }
        public int EmplCodigo { get; set; }
        public string KigaDescrip { get; set; }
        public string comaNumero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
    }
}
