//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaGrupo
    {
        public string Emprcod { get; set; }
        public string LproCodigo { get; set; }
        public string GproCodigo { get; set; }
        public Nullable<int> LinGOrden { get; set; }
    }
}
