//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListP
    {
        public string ListCodigo { get; set; }
        public string EmprCod { get; set; }
        public string ListNombre { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<int> ListCpaVta { get; set; }
        public Nullable<short> ListImpto { get; set; }
        public Nullable<short> ListPor { get; set; }
        public Nullable<double> ListMonto { get; set; }
        public Nullable<short> ListCostoImp { get; set; }
        public Nullable<short> ListCantDec { get; set; }
        public Nullable<short> ListModPrecioEnVta { get; set; }
        public Nullable<double> ListValmMonto { get; set; }
        public Nullable<short> ListPMPVenta { get; set; }
        public string ListMonCompra { get; set; }
    }
}
