//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStock
    {
        public Nullable<double> NumEnc { get; set; }
        public string Producto { get; set; }
        public string Cantidad { get; set; }
        public string Empresas { get; set; }
        public string Sucursal { get; set; }
        public string Movimiento { get; set; }
        public string TipoDoc { get; set; }
        public string Rut { get; set; }
        public string Mes { get; set; }
        public string Ano { get; set; }
        public string Stock { get; set; }
        public int Codigo { get; set; }
    }
}
