//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantencionesProducto
    {
        public int maprCodigo { get; set; }
        public string modeCodigo { get; set; }
        public short mamoAno { get; set; }
        public int mamoKilometraje { get; set; }
        public string prodCodigo { get; set; }
        public string EmprCod { get; set; }
        public Nullable<double> mmprCantidad { get; set; }
        public short maprCorrel { get; set; }
    }
}
