//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelosProd
    {
        public string ModeCodigo { get; set; }
        public string ModeNombre { get; set; }
        public int ModeAno { get; set; }
        public short MproCodigo { get; set; }
    }
}
