//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificacionesFormulario
    {
        public string EmprCod { get; set; }
        public string ProyCodigo { get; set; }
        public string MandCodigo { get; set; }
        public string EtapCodigo { get; set; }
        public int FormNumero { get; set; }
        public System.DateTime FormFecha { get; set; }
        public string FormGlosa { get; set; }
        public string UsuaCodigo { get; set; }
    }
}
