//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontoCargaFamiliar
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short MCFAno { get; set; }
        public short MCFMes { get; set; }
        public Nullable<double> MCFEnero { get; set; }
        public Nullable<double> MCFFebrero { get; set; }
        public Nullable<double> MCFMarzo { get; set; }
        public Nullable<double> MCFAbril { get; set; }
        public Nullable<double> MCFMayo { get; set; }
        public Nullable<double> MCFJunio { get; set; }
        public Nullable<double> MCFJulio { get; set; }
        public Nullable<double> MCFAgosto { get; set; }
        public Nullable<double> MCFSeptiembre { get; set; }
        public Nullable<double> MCFOctubre { get; set; }
        public Nullable<double> MCFNoviembre { get; set; }
        public Nullable<double> MCFDiciembre { get; set; }
    }
}
