//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontosMetasReponedore
    {
        public Nullable<int> DoctMes { get; set; }
        public Nullable<int> DoctAno { get; set; }
        public string RelcRut { get; set; }
        public bool RelcExtranjero { get; set; }
        public string RelcNombre { get; set; }
        public string NombreSupervisor { get; set; }
        public string NombreReponedor { get; set; }
        public string CodigoSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string CodigoLinea { get; set; }
        public string NombreLinea { get; set; }
        public string CodigoMarca { get; set; }
        public string NombreMarca { get; set; }
        public string CodigoProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public string Vendedor { get; set; }
    }
}
