//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosCaBa
    {
        public string EmprCod { get; set; }
        public string InstCodigo { get; set; }
        public string IfemNumeroCuenta { get; set; }
        public int CabaNumero { get; set; }
        public int MocbCorrelativo { get; set; }
        public Nullable<System.DateTime> MocbFecha { get; set; }
        public string MocbNroDocumento { get; set; }
        public string MocbGlosa { get; set; }
        public Nullable<double> MocbCargo { get; set; }
        public Nullable<double> MocbAbono { get; set; }
        public string MocbCodMovimiento { get; set; }
        public Nullable<double> CocoTipmMonto { get; set; }
        public string CtaCCodigo { get; set; }
    }
}
