//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO_ACTIVOS_FIJOS
    {
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public string Empresa { get; set; }
        public string Codigo { get; set; }
        public string SI_ES_NETO { get; set; }
        public string TIPO { get; set; }
        public Nullable<double> Valor_tributable { get; set; }
        public Nullable<double> Valor_contable { get; set; }
        public string Reversa { get; set; }
    }
}
