//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_WMS
    {
        public decimal idmovimiento { get; set; }
        public string Documento { get; set; }
        public Nullable<decimal> Numero_documento { get; set; }
        public Nullable<int> Linea_solicitada { get; set; }
        public string Documento_solicitado { get; set; }
        public Nullable<decimal> Numero_documento_solicitado { get; set; }
        public string Tipo_movimiento { get; set; }
        public string Documento_respaldo { get; set; }
        public string Numero_documento_respaldo { get; set; }
        public string Documento_respaldo_solicitado { get; set; }
        public string Numero_documento_respaldo_solicitado { get; set; }
        public string Empresa { get; set; }
        public string Entidad { get; set; }
        public string Bodega { get; set; }
        public Nullable<System.DateTime> Fecha_movimiento { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> Entrada { get; set; }
        public Nullable<decimal> Salida { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> Fecha_elaboracion { get; set; }
        public Nullable<System.DateTime> Fecha_vencimiento { get; set; }
        public string Serie { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Variable1 { get; set; }
        public string Variable2 { get; set; }
        public string Variable3 { get; set; }
        public string Variable4 { get; set; }
        public string Variable5 { get; set; }
        public string Identificador_erp { get; set; }
        public Nullable<int> Numero_oleada { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public string Usuario_creacion { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public Nullable<short> Procesado { get; set; }
    }
}
