//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_solicitado
    {
        public string Documento_solicitado { get; set; }
        public decimal Numero_documento_solicitado { get; set; }
        public string Tipo_movimiento { get; set; }
        public string Clasificacion_movimiento { get; set; }
        public Nullable<System.DateTime> Fecha_movimiento { get; set; }
        public Nullable<System.DateTime> Fecha_programada { get; set; }
        public string Documento_solicitado_asociado { get; set; }
        public Nullable<decimal> Numero_documento_solicitado_asociado { get; set; }
        public Nullable<int> Numero_oleada { get; set; }
        public string Responsable { get; set; }
        public string Motivo_asociado { get; set; }
        public string Empresa { get; set; }
        public string Entidad { get; set; }
        public string Sucursal { get; set; }
        public Nullable<decimal> Contacto { get; set; }
        public string Documento_respaldo { get; set; }
        public string Numero_documento_respaldo { get; set; }
        public string Orden_compra { get; set; }
        public string Nota_venta { get; set; }
        public string Bodega { get; set; }
        public string Bodega_erp { get; set; }
        public string Identificador_erp { get; set; }
        public Nullable<System.DateTime> Fecha_autorizacion { get; set; }
        public string Usuario_autorizacion { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Session_id { get; set; }
        public string Notas { get; set; }
        public string Estado { get; set; }
        public string Usuario_creacion { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public string Usuario_modificacion { get; set; }
        public Nullable<System.DateTime> Fecha_modificacion { get; set; }
    }
}
