//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovLinea
    {
        public double MostNro { get; set; }
        public string EmprCod { get; set; }
        public short MostCAno { get; set; }
        public string ProdCod { get; set; }
        public string PbarCodigo { get; set; }
        public double MostCorrel { get; set; }
        public Nullable<double> MoLinCantidad { get; set; }
        public Nullable<double> MoLinPrecioNeto { get; set; }
        public Nullable<double> MoLinTotalL { get; set; }
        public string MineCodigo { get; set; }
        public string FuncCodigo { get; set; }
        public string CodPlantilla { get; set; }
        public Nullable<double> MostConversion { get; set; }
        public string ProdCodOriDes { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string CtaCCodigo { get; set; }
        public string CodrCodigo { get; set; }
        public Nullable<double> MovTraspaso { get; set; }
        public string MostCodigo { get; set; }
        public string MostCodOper { get; set; }
    }
}
