//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovMensualLinea
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short HabDesAno { get; set; }
        public short HabDesMes { get; set; }
        public int MovMenCorrel { get; set; }
        public int MovMenlLineas { get; set; }
        public string MovMenCodigo { get; set; }
        public Nullable<System.DateTime> MovMenFechaInicial { get; set; }
        public Nullable<System.DateTime> MovMenFechaTermino { get; set; }
    }
}
