//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovsCuota
    {
        public string EmprCod { get; set; }
        public short MovsAno { get; set; }
        public string SucuCodigo { get; set; }
        public string MovsTipo { get; set; }
        public string MovsMTE { get; set; }
        public int MovsCorrelCuota { get; set; }
        public string RelcRut { get; set; }
        public double MovsNumero { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<short> MovsMes { get; set; }
        public Nullable<short> MovsEstado { get; set; }
        public Nullable<System.DateTime> MovsVencCuota { get; set; }
        public Nullable<System.DateTime> MovsFechaTrans { get; set; }
        public Nullable<double> MovsSaldoCuota { get; set; }
        public Nullable<double> MovsMontoCuota { get; set; }
    }
}
