//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovsPago
    {
        public string EmprCod { get; set; }
        public short MovsAno { get; set; }
        public double MovsNumero { get; set; }
        public short MovsCorrelCuota { get; set; }
        public short MovsCorrel { get; set; }
        public string MovsTipo { get; set; }
        public string RelcRut { get; set; }
        public string SucuCodigo { get; set; }
        public short RelcExtranjero { get; set; }
        public string MovsMTE { get; set; }
        public Nullable<byte> MostEntSal { get; set; }
        public Nullable<System.DateTime> MovsFechaP { get; set; }
        public Nullable<double> MovsMonto { get; set; }
        public string MovsGlosa { get; set; }
        public string MovsNroDoc { get; set; }
        public string MovsAux { get; set; }
        public string UsrsCodigo { get; set; }
        public Nullable<short> MovsMes { get; set; }
        public string TpagCodigo { get; set; }
        public string InstCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<short> PtovCodigo { get; set; }
        public Nullable<double> ApeCodigo { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<short> MovsEstado { get; set; }
        public Nullable<short> SuccCodigo { get; set; }
        public string MovsDes { get; set; }
        public Nullable<short> MovsCartera { get; set; }
        public Nullable<double> MovsMtoTotalDoc { get; set; }
        public Nullable<System.DateTime> MovsFechaVen { get; set; }
        public string BpagCtaCorriente { get; set; }
        public string BpagPlaza { get; set; }
        public string BpagRutOri { get; set; }
        public Nullable<short> BpagExtOri { get; set; }
    }
}
