//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NM_VIEW_CRM_ATRIB_ADIC_RESERVAS
    {
        public string NomTipoVisita { get; set; }
        public string AtadCodigo { get; set; }
        public Nullable<int> OdliCorrLinea { get; set; }
        public string RelcRut { get; set; }
        public string RelcExtranjero { get; set; }
        public Nullable<int> OdocMovimiento { get; set; }
        public Nullable<int> OdocNumero { get; set; }
        public string valor { get; set; }
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
    }
}
