//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NM_VIEW_RESERVAS_SOPORTE
    {
        public string EmprCod { get; set; }
        public string RelcRut { get; set; }
        public string RelcNombre { get; set; }
        public string RelcGiro { get; set; }
        public Nullable<System.DateTime> Fecha_reserva { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string EmplNomCompleto { get; set; }
        public string OdocObservacion { get; set; }
        public short Modulo { get; set; }
        public Nullable<System.DateTime> HoraIniModulo { get; set; }
        public string ProdCodigo { get; set; }
        public string ProdNombre { get; set; }
        public double OdocNumero { get; set; }
        public Nullable<double> Costo_Movilizacion { get; set; }
        public string Tipo_Visita { get; set; }
        public string Visita_suspendida { get; set; }
        public string Motivo_Suspension { get; set; }
    }
}
