//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaVta
    {
        public string EmprCod { get; set; }
        public short NvAno { get; set; }
        public short NvMes { get; set; }
        public string SucuCodigo { get; set; }
        public int NvPtoVenta { get; set; }
        public double NvNumero { get; set; }
        public string AlmaCodigo { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<double> NvTotal { get; set; }
        public Nullable<System.DateTime> NvFechaIngreso { get; set; }
        public Nullable<System.DateTime> NvFechaVenc { get; set; }
        public string NvGlosa { get; set; }
    }
}
