//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class novaConfigCuenta
    {
        public string emprCod { get; set; }
        public short noccAno { get; set; }
        public string noccCodSistema { get; set; }
        public Nullable<short> isEneroClose { get; set; }
        public Nullable<short> isFebreroClose { get; set; }
        public Nullable<short> isMarzoClose { get; set; }
        public Nullable<short> isAbrilClose { get; set; }
        public Nullable<short> isMayoClose { get; set; }
        public Nullable<short> isJunioClose { get; set; }
        public Nullable<short> isJulioClose { get; set; }
        public Nullable<short> isAgostoClose { get; set; }
        public Nullable<short> isSeptiembreClose { get; set; }
        public Nullable<short> isOctubreClose { get; set; }
        public Nullable<short> isNoviembreClose { get; set; }
        public Nullable<short> isDiciembreClose { get; set; }
        public string noccOPAAux { get; set; }
        public string noccNomLargo { get; set; }
        public Nullable<short> noccCtaCActivo { get; set; }
        public Nullable<short> noccCtaCPasivo { get; set; }
        public Nullable<short> noccCtaCPerdida { get; set; }
        public Nullable<short> noccCtaCGanancia { get; set; }
        public Nullable<short> noccHabilitado { get; set; }
        public Nullable<short> IsAnoClose { get; set; }
        public Nullable<System.DateTime> noccFechaTraspaso { get; set; }
        public string noccRespTraspaso { get; set; }
        public string noccProveniente { get; set; }
        public string UsrsCodigoPredeterminado { get; set; }
        public Nullable<int> noccNumMovimientos { get; set; }
        public Nullable<short> isEneroLocked { get; set; }
        public Nullable<short> isFebreroLocked { get; set; }
        public Nullable<short> isMarzoLocked { get; set; }
        public Nullable<short> isAbrilLocked { get; set; }
        public Nullable<short> isMayoLocked { get; set; }
        public Nullable<short> isJunioLocked { get; set; }
        public Nullable<short> isJulioLocked { get; set; }
        public Nullable<short> isAgostoLocked { get; set; }
        public Nullable<short> isSeptiembreLocked { get; set; }
        public Nullable<short> isOctubreLocked { get; set; }
        public Nullable<short> isNoviembreLocked { get; set; }
        public Nullable<short> isDiciembreLocked { get; set; }
        public Nullable<double> noccEneroReservaComp { get; set; }
        public Nullable<double> noccFebreroReservaComp { get; set; }
        public Nullable<double> noccMarzoReservaComp { get; set; }
        public Nullable<double> noccAbrilReservaComp { get; set; }
        public Nullable<double> noccMayoReservaComp { get; set; }
        public Nullable<double> noccJunioReservaComp { get; set; }
        public Nullable<double> noccJulioReservaComp { get; set; }
        public Nullable<double> noccAgostoReservaComp { get; set; }
        public Nullable<double> noccSeptiembreReservaComp { get; set; }
        public Nullable<double> noccOctubreReservaComp { get; set; }
        public Nullable<double> noccNoviembreReservaComp { get; set; }
        public Nullable<double> noccDiciembreReservaComp { get; set; }
        public Nullable<int> noccMesActivo { get; set; }
    }
}
