//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvLinea
    {
        public string EmprCod { get; set; }
        public short NvAno { get; set; }
        public short NvMes { get; set; }
        public string SucuCodigo { get; set; }
        public int NvPtoVenta { get; set; }
        public double NvNumero { get; set; }
        public int NvlCorrLinea { get; set; }
        public string ProdCodigo { get; set; }
        public string PbarCodigo { get; set; }
        public Nullable<double> NvlCantidad { get; set; }
        public Nullable<int> NvlPrecio { get; set; }
        public Nullable<int> NvlDescto { get; set; }
        public Nullable<int> NvlTotal { get; set; }
        public Nullable<short> NvEsKit { get; set; }
        public Nullable<double> NvlPrecioNeto { get; set; }
        public Nullable<int> NvlTotalNeto { get; set; }
    }
}
