//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODdistribucion
    {
        public string EmprCOd { get; set; }
        public short OdliCorrLinea { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public string OdocNumero { get; set; }
        public short OdocLinea { get; set; }
        public Nullable<double> Semana1 { get; set; }
        public Nullable<double> Semana2 { get; set; }
        public Nullable<double> Semana3 { get; set; }
        public Nullable<double> Semana4 { get; set; }
        public Nullable<double> Semana5 { get; set; }
        public Nullable<System.DateTime> Fecha1 { get; set; }
        public Nullable<System.DateTime> Fecha2 { get; set; }
        public Nullable<System.DateTime> Fecha3 { get; set; }
        public Nullable<System.DateTime> Fecha4 { get; set; }
        public Nullable<System.DateTime> Fecha5 { get; set; }
        public string OdLote { get; set; }
        public Nullable<System.DateTime> OdFVence { get; set; }
        public Nullable<System.DateTime> OdFElaboracion { get; set; }
        public Nullable<double> CorrelativoID { get; set; }
        public Nullable<double> TipoCambioDefinitivoLinea { get; set; }
        public Nullable<double> TipoCambioProvisorioLinea { get; set; }
    }
}
