//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODImpto
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public string TdocCodigo { get; set; }
        public double OdocNumero { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string ImpuCodigo { get; set; }
        public Nullable<short> OdimAno { get; set; }
        public Nullable<double> OdocImpTasa { get; set; }
        public Nullable<double> OdocImpBase { get; set; }
        public Nullable<double> OdocImpMonto { get; set; }
        public Nullable<double> OdimMontoRec { get; set; }
        public Nullable<double> OdimBaseRec { get; set; }
    }
}
