//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODLineasExt
    {
        public string EmprCod { get; set; }
        public short OdliCorrLinea { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public double OdocNumero { get; set; }
        public string ProdCodigo { get; set; }
        public Nullable<double> OdliExt1 { get; set; }
        public Nullable<double> OdliExt2 { get; set; }
        public Nullable<double> OdliExt3 { get; set; }
        public Nullable<double> OdliExt4 { get; set; }
        public Nullable<double> OdliExt5 { get; set; }
        public Nullable<double> OdliExt6 { get; set; }
        public Nullable<double> OdliExt7 { get; set; }
        public Nullable<double> OdliExt8 { get; set; }
        public Nullable<double> OdliExt9 { get; set; }
    }
}
