//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODLinea
    {
        public string EmprCod { get; set; }
        public short OdliCorrLinea { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public double OdocNumero { get; set; }
        public string ProdCodigo { get; set; }
        public string PbarCodigo { get; set; }
        public Nullable<short> OdliAno { get; set; }
        public Nullable<double> OdliPrecioBruto { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<double> OdliDescuento { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> OdliCantidad { get; set; }
        public Nullable<double> OdliTotalLinea { get; set; }
        public Nullable<int> OdliTipCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<double> OdliPrecioNeto { get; set; }
        public Nullable<double> OdliMontoOrig { get; set; }
        public Nullable<short> OdliTieRelac { get; set; }
        public Nullable<int> OdliFactorC { get; set; }
        public string CtaCCodigo { get; set; }
        public string CodrCodigo { get; set; }
        public Nullable<double> OdliPreFinal { get; set; }
        public string OdliKitCod { get; set; }
        public Nullable<short> OdliKitCorrel { get; set; }
        public Nullable<double> OdliSubTotalBruto { get; set; }
        public string UnimCodigo { get; set; }
        public Nullable<double> UMPEquivalencia { get; set; }
        public Nullable<double> OdliPrecioBrutoOriginal { get; set; }
        public string OdocClasificacion { get; set; }
        public string OdocNoDespacho { get; set; }
        public Nullable<int> OdocOrigen { get; set; }
        public string OdocDescTipo { get; set; }
    }
}
