//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdocValDestino
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public double OdocNumero { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string DestCodigo { get; set; }
        public Nullable<double> OdocDestValor { get; set; }
        public string OdocDestRutTrans { get; set; }
        public short OdocDestExtTrans { get; set; }
    }
}
