//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPProductosInvolucrado
    {
        public string operCodigo { get; set; }
        public string otopCodigo { get; set; }
        public string prodCodigo { get; set; }
        public int prodAno { get; set; }
        public string EmprCod { get; set; }
    }
}
