//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTiposOperacion
    {
        public string otopCodigo { get; set; }
        public string otopNombre { get; set; }
        public string otopReporteDetalle { get; set; }
        public string otopReporteResumen { get; set; }
        public string otopReporteAlternativo { get; set; }
    }
}
