//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTiposMovimiento
    {
        public string otmoCodigo { get; set; }
        public string otopCodigo { get; set; }
        public string otmoNombre { get; set; }
        public string otmoTablaOrigen { get; set; }
        public string otmoCampoLlave1 { get; set; }
        public string otmoCampoLlave2 { get; set; }
        public string otmoCampoLlave3 { get; set; }
        public string otmoCampoLlave4 { get; set; }
        public string otmoCampoLlave5 { get; set; }
        public string otmoCampoLlave6 { get; set; }
        public string otmoCampoLlave7 { get; set; }
        public string otmoCampoLlave8 { get; set; }
        public string otmoCampoLlave9 { get; set; }
        public string otmoCampoLlave10 { get; set; }
    }
}
