//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_DE_COMPRA_Y_OTROS_COMPRAS_COSTOS
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string Cod_TipoDocumento { get; set; }
        public string Desc_TipoDocumento { get; set; }
        public short Tipo_Movimiento { get; set; }
        public string Desc_TipoMovimiento { get; set; }
        public double Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> F_Vencimiento { get; set; }
        public string Rut { get; set; }
        public short Extranjero { get; set; }
        public string Nombre_CliProv { get; set; }
        public Nullable<double> Sucursal { get; set; }
        public string NomSucursal { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<short> CodVendedor { get; set; }
        public string NomVendedor { get; set; }
        public Nullable<short> Doc_Cerrado { get; set; }
        public string CodListP { get; set; }
        public string NomListP { get; set; }
        public string CodTipoPago { get; set; }
        public string NomTipoPago { get; set; }
        public string PlazoPago { get; set; }
        public string Cod_Producto { get; set; }
        public string Nom_Producto { get; set; }
        public string LineaProducto { get; set; }
        public string Departamento { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public Nullable<double> UnidadesSL { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<double> PrecioUnitarioNeto { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> PrecioUnitFinal { get; set; }
        public Nullable<double> PrecioNetoTotFinal { get; set; }
        public Nullable<double> PrecioBrutoTotal { get; set; }
        public string Observaciones { get; set; }
        public string FechaDespacho { get; set; }
        public string DocuAsociado { get; set; }
        public string DirDespacho { get; set; }
        public Nullable<double> Cre_Disponible { get; set; }
        public Nullable<double> CantPendiente { get; set; }
        public int Recibida_Lote { get; set; }
        public string EsParteKit { get; set; }
        public Nullable<short> codregion { get; set; }
        public string nomregion { get; set; }
        public Nullable<short> codciudad { get; set; }
        public string nomciudad { get; set; }
        public Nullable<short> codcomuna { get; set; }
        public string nomcomuna { get; set; }
        public string OdocOC { get; set; }
        public Nullable<double> CajasPendientes { get; set; }
        public Nullable<double> VentaPendiente { get; set; }
        public Nullable<double> KilosPendiente { get; set; }
        public string NroLote { get; set; }
        public string FECHA_VENCIMIENTO_LOTE { get; set; }
        public Nullable<decimal> OC { get; set; }
        public string CuentaContable { get; set; }
        public string CodCentroResultado { get; set; }
        public string CentroResultado { get; set; }
        public string Glosa1 { get; set; }
        public string Glosa2 { get; set; }
        public string Glosa3 { get; set; }
        public Nullable<int> NroSemana { get; set; }
        public string FECHA_ELABORACION { get; set; }
        public string FECHA_VENCIMIENTO { get; set; }
        public short Correlativo { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public string ViaLLegada { get; set; }
        public string Clausula { get; set; }
        public Nullable<double> NumeroCarpeta { get; set; }
        public string UnidMedida { get; set; }
        public Nullable<double> CantCONTENEDORES { get; set; }
        public Nullable<double> FletePuerto { get; set; }
        public Nullable<double> FleteInternacional { get; set; }
        public Nullable<double> TOTALKILOS { get; set; }
        public Nullable<double> USDUnitario { get; set; }
        public Nullable<double> TotalUSD { get; set; }
        public Nullable<double> USD_Unitario_Kilo { get; set; }
        public Nullable<double> USD_Unitario_Flete_Kilo { get; set; }
        public Nullable<double> USD_Unitario_CFR_Kilo { get; set; }
        public Nullable<double> Porcentaje_gasto { get; set; }
        public Nullable<double> COSTOS_USD { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public Nullable<double> CostoPesos { get; set; }
        public Nullable<short> CostosDefinitivo { get; set; }
    }
}
