//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_DE_COMPRA_Y_OTROS_COMPRAS_LINEA_GENERAL
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string Desc_TipoMovimiento { get; set; }
        public Nullable<double> Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> F_Vencimiento { get; set; }
        public string Rut { get; set; }
        public Nullable<short> Extranjero { get; set; }
        public string Nombre_CliProv { get; set; }
        public string Cod_Producto { get; set; }
        public string Nom_Producto { get; set; }
        public string LineaProducto { get; set; }
        public string Marca { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> PrecioUnitarioNeto { get; set; }
        public string Cuenta { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public Nullable<double> PrecioNetoTotFinal { get; set; }
        public Nullable<double> PrecioBrutoTotal { get; set; }
        public string Observaciones { get; set; }
        public string Descripcion_Extendida { get; set; }
        public string CodCentroResultado { get; set; }
        public string CentroResultado { get; set; }
        public string Glosa1 { get; set; }
        public string Glosa2 { get; set; }
        public string Glosa3 { get; set; }
        public Nullable<int> NroSemana { get; set; }
    }
}
