//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_DE_COMPRA_Y_OTROS_COMPRAS_ABASTECIMIENTO_DP
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public string Cod_TipoDocumento { get; set; }
        public string Desc_TipoDocumento { get; set; }
        public Nullable<short> Tipo_Movimiento { get; set; }
        public string Desc_TipoMovimiento { get; set; }
        public Nullable<double> Numero { get; set; }
        public string Rut { get; set; }
        public Nullable<short> Extranjero { get; set; }
        public string Nombre_CliProv { get; set; }
        public Nullable<short> CodVendedor { get; set; }
        public string NomVendedor { get; set; }
        public string Cod_Producto { get; set; }
        public string Nom_Producto { get; set; }
        public string LineaProducto { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<double> PrecioUnitarioNeto { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public Nullable<double> PrecioNetoTotFinal { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> CantPendiente { get; set; }
        public int Recibida_Lote { get; set; }
        public Nullable<double> CajasPendientes { get; set; }
        public Nullable<double> VentaPendiente { get; set; }
        public Nullable<double> KilosPendiente { get; set; }
        public Nullable<decimal> OC { get; set; }
        public string Glosa1 { get; set; }
        public string Glosa2 { get; set; }
        public string Glosa3 { get; set; }
        public Nullable<int> NroSemana { get; set; }
        public string F1_OC { get; set; }
        public int Semana1_OC { get; set; }
        public string F2_OC { get; set; }
        public int Semana2_OC { get; set; }
        public string F3_OC { get; set; }
        public int Semana3_OC { get; set; }
        public string F4_OC { get; set; }
        public int Semana4_OC { get; set; }
        public string F5_OC { get; set; }
        public int Semana5_OC { get; set; }
        public Nullable<System.DateTime> F1_DP { get; set; }
        public Nullable<double> Semana1_DP { get; set; }
        public Nullable<System.DateTime> F2_DP { get; set; }
        public Nullable<double> Semana2_DP { get; set; }
        public Nullable<System.DateTime> F3_DP { get; set; }
        public Nullable<double> Semana3_DP { get; set; }
        public Nullable<System.DateTime> F4_DP { get; set; }
        public Nullable<double> Semana4_DP { get; set; }
        public Nullable<System.DateTime> F5_DP { get; set; }
        public Nullable<double> Semana5_DP { get; set; }
        public string F1_PF { get; set; }
        public int Semana1_PF { get; set; }
        public string F2_PF { get; set; }
        public int Semana2_PF { get; set; }
        public string F3_PF { get; set; }
        public int Semana3_PF { get; set; }
        public string F4_PF { get; set; }
        public int Semana4_PF { get; set; }
        public string F5_PF { get; set; }
        public int Semana5_PF { get; set; }
        public string F1_GD { get; set; }
        public int Semana1_GD { get; set; }
        public string F2_GD { get; set; }
        public int Semana2_GD { get; set; }
        public string F3_GD { get; set; }
        public int Semana3_GD { get; set; }
        public string F4_GD { get; set; }
        public int Semana4_GD { get; set; }
        public string F5_GD { get; set; }
        public int Semana5_GD { get; set; }
        public string TipoDocOC { get; set; }
        public Nullable<double> NumeroOC { get; set; }
        public string ProductoOC { get; set; }
        public Nullable<double> CantidadOC { get; set; }
        public string TipoDocDP { get; set; }
        public Nullable<double> NumeroDP { get; set; }
        public string ProductoDP { get; set; }
        public Nullable<double> CantidadDP { get; set; }
        public int TipoDocPF { get; set; }
        public int NumeroPF { get; set; }
        public string ProductoPF { get; set; }
        public int CantidadPF { get; set; }
        public int TipoDocGD { get; set; }
        public int NumeroGD { get; set; }
        public string ProductoGD { get; set; }
        public int CantidadGD { get; set; }
        public string NuevaOC { get; set; }
        public string ORDEN { get; set; }
        public int Total_OC { get; set; }
        public int Total_PF { get; set; }
        public Nullable<double> Total_DP { get; set; }
        public int Total_GD { get; set; }
        public int Saldo_OC { get; set; }
        public Nullable<double> Saldo_DP { get; set; }
        public int Saldo_PF { get; set; }
        public int Saldo_GD { get; set; }
    }
}
