//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_DE_COMPRA_Y_OTROS_ANALISTA
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public double OdocNumero { get; set; }
        public string documentosOP { get; set; }
        public string RelcRut { get; set; }
        public Nullable<double> INVANumero { get; set; }
        public Nullable<int> PalmMes { get; set; }
        public Nullable<int> PalmAno { get; set; }
        public string NOM_LOTE { get; set; }
        public string DOCUMENTO_string { get; set; }
        public Nullable<double> CANTIDAD_CAJAS_LOTE { get; set; }
        public string ProdCodigo { get; set; }
    }
}
