//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrtrLinea
    {
        public string EmprCod { get; set; }
        public int OrtrNumero { get; set; }
        public int OtliCorrelativo { get; set; }
        public string ProdCodigo { get; set; }
        public int OrtrAno { get; set; }
        public Nullable<double> OtliCantidad { get; set; }
        public string PagaRut { get; set; }
        public Nullable<short> PagaExtranjero { get; set; }
        public string PagaTipo { get; set; }
        public Nullable<double> OrtlMontoUnitario { get; set; }
        public Nullable<double> OrtlMontoLinea { get; set; }
        public string OrtlCodRealiza { get; set; }
        public string caprCodigo { get; set; }
        public Nullable<double> OrtrCodigo { get; set; }
    }
}
