//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosAnticipado
    {
        public string TpagCodigo { get; set; }
        public string EmprCod { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public double PagoCorrel { get; set; }
        public Nullable<double> PagoDisponible { get; set; }
        public Nullable<double> PagoUtilizado { get; set; }
        public Nullable<System.DateTime> PagoFecha { get; set; }
        public Nullable<double> ApeCodigo { get; set; }
        public Nullable<double> BoleNumero { get; set; }
        public Nullable<short> PtovCodigo { get; set; }
        public Nullable<System.DateTime> PagoFechaVenc { get; set; }
    }
}
