//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PantallaComex
    {
        public string ComId { get; set; }
        public string EmprCod { get; set; }
        public string ComAno { get; set; }
        public string ComMes { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public string RelcRut { get; set; }
        public Nullable<decimal> ComTcAduana { get; set; }
        public string ComFactura { get; set; }
        public string ComDespacho { get; set; }
        public Nullable<System.DateTime> ComFecha { get; set; }
        public string ComCarpeta { get; set; }
        public Nullable<decimal> ComValorFob { get; set; }
        public Nullable<decimal> ComGHF { get; set; }
        public Nullable<decimal> ComAjuste1 { get; set; }
        public Nullable<decimal> ComFlete { get; set; }
        public Nullable<decimal> ComSeguro { get; set; }
        public Nullable<decimal> ComCIF { get; set; }
        public Nullable<decimal> ComMuestraSAG { get; set; }
        public Nullable<decimal> ComSNS { get; set; }
        public Nullable<decimal> ComIngGastosFact1 { get; set; }
        public Nullable<decimal> ComIngGastosFact2 { get; set; }
        public Nullable<decimal> ComIngGastosFact3 { get; set; }
        public Nullable<decimal> ComIngGastosFact4 { get; set; }
        public Nullable<decimal> ComIVA { get; set; }
        public Nullable<decimal> ComKilos { get; set; }
        public Nullable<decimal> ComTotalDesembolso { get; set; }
        public Nullable<decimal> ComAjuste2 { get; set; }
        public Nullable<decimal> ComTotalDesembolsoFinal { get; set; }
    }
}
