//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetesExportacion
    {
        public string PaExCodigo { get; set; }
        public string PaExTabla { get; set; }
        public string PaExSQL { get; set; }
        public string PaExSQL2 { get; set; }
        public string PaExSQL3 { get; set; }
        public string PaExConexion { get; set; }
        public double PaExCorrelativo { get; set; }
        public string PaExDescripcion { get; set; }
    }
}
