//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParaUsuarioGrupo
    {
        public string pugrCodigo { get; set; }
        public string pugrNombre { get; set; }
        public string UsrsCodigo { get; set; }
        public string repoSistema { get; set; }
        public int repoIndice { get; set; }
    }
}
