//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroReporte
    {
        public string repoSistema { get; set; }
        public int repoIndice { get; set; }
        public string pareNombre { get; set; }
        public int pareIndice { get; set; }
        public Nullable<short> pareEsLOV { get; set; }
        public Nullable<int> retiCodigo { get; set; }
        public Nullable<int> rptpCodigo { get; set; }
        public string pareLOVNombreCampo { get; set; }
        public string pareLOVNombreDescripcion { get; set; }
        public string pareLOVTabla { get; set; }
        public string pareLOVStringSelect { get; set; }
        public Nullable<short> pareLOVUsaEmpr { get; set; }
        public Nullable<short> pareRequerido { get; set; }
        public string pareLOVBase { get; set; }
    }
}
