//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlccLinea
    {
        public string EmprCod { get; set; }
        public string PlccCodigo { get; set; }
        public int PcliItem { get; set; }
        public string CtaCDebe { get; set; }
        public string CtaCHaber { get; set; }
        public Nullable<int> PcliDebeHaber { get; set; }
        public string PcliGlosaLinea { get; set; }
        public string TpreCodigo { get; set; }
        public string PritCodigo { get; set; }
    }
}
