//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMPProductoMoneda
    {
        public string EmprCod { get; set; }
        public string ProdCodigo { get; set; }
        public short ProdAno { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> PMPPCantidad { get; set; }
        public Nullable<double> PMPPStockValorizado { get; set; }
        public Nullable<double> PMPPPrecioMP { get; set; }
    }
}
