//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoGaLinea
    {
        public string EmprCod { get; set; }
        public int PogaNumero { get; set; }
        public int PoliItem { get; set; }
        public string PoliOrigen { get; set; }
        public Nullable<System.DateTime> PoliFecha { get; set; }
        public string PoliGlosa { get; set; }
        public Nullable<double> PoliAbono { get; set; }
        public Nullable<double> PoliCargo { get; set; }
        public Nullable<int> PoliNula { get; set; }
        public Nullable<double> PoliSaldo { get; set; }
        public Nullable<double> PoliSaldoReal { get; set; }
    }
}
