//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios_Productos_y_Kits
    {
        public string ProdCodigo { get; set; }
        public string ListCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ValPAno { get; set; }
        public Nullable<double> ValpNeto { get; set; }
        public Nullable<double> ValpBruto { get; set; }
        public Nullable<double> ValPMargenReal { get; set; }
        public int EsKit { get; set; }
    }
}
