//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public string EmprCod { get; set; }
        public string TipeCodigo { get; set; }
        public string PresCodigo { get; set; }
        public string PresNombre { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> PresTipmMonto { get; set; }
        public Nullable<System.DateTime> PresFechaInicio { get; set; }
    }
}
