//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresLinea
    {
        public string EmprCod { get; set; }
        public string TipeCodigo { get; set; }
        public string PresCodigo { get; set; }
        public string ItprCodigo { get; set; }
        public int PrliPeriodo { get; set; }
        public Nullable<double> PrliMto { get; set; }
        public Nullable<double> PrliMtoMonOri { get; set; }
        public Nullable<System.DateTime> PrliFechaInicio { get; set; }
        public Nullable<System.DateTime> PrliFechaTermino { get; set; }
    }
}
