//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAlmacenExt
    {
        public string ProdCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public string EmprCod { get; set; }
        public short PalmAno { get; set; }
        public short PalmMes { get; set; }
        public int PalmExCorrel { get; set; }
        public Nullable<double> PalmExCantidad { get; set; }
        public string PalmExPosicion { get; set; }
        public Nullable<short> PalmExEntSal { get; set; }
    }
}
