//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdBarra
    {
        public string PbarCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public string EmprCod { get; set; }
        public short PbarAno { get; set; }
        public string PbarNombre { get; set; }
        public string PbarCodificacion { get; set; }
        public string PbarCodigoAlt1 { get; set; }
        public string PbarCodigoAlt2 { get; set; }
        public string PbarCodigoAlt3 { get; set; }
        public string PbarNombreAlt1 { get; set; }
        public string PbarNombreAlt2 { get; set; }
        public string PbarNombreAlt3 { get; set; }
        public string DiasEntrega { get; set; }
        public string CodigoPais { get; set; }
        public string ArchivoRuta { get; set; }
        public string Tcpt_Cod { get; set; }
    }
}
