//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdRelacCom
    {
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string ProdCodigo { get; set; }
        public string EmprCod { get; set; }
        public short PrcoAno { get; set; }
        public string PrcoProdCod { get; set; }
        public string PrcoProdNom { get; set; }
        public Nullable<short> PrcoProdDesc { get; set; }
        public Nullable<int> PrcoFrecuencia { get; set; }
        public Nullable<int> PrcoCategoria { get; set; }
        public string PrcoTipo { get; set; }
    }
}
