//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAlmacenProyeccionLote
    {
        public string ProdCodigo { get; set; }
        public string AlmaCodigo { get; set; }
        public string EmprCod { get; set; }
        public short PalmAno { get; set; }
        public short PalmMes { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public string NroLote { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> VentaDiaria { get; set; }
        public Nullable<double> DiasInventario { get; set; }
        public Nullable<double> StockRetenido { get; set; }
        public Nullable<double> DiasInventarioRetenido { get; set; }
        public Nullable<double> VentaTotal { get; set; }
    }
}
