//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdExtendido
    {
        public string ProdCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ProdAno { get; set; }
        public int PrExPagina { get; set; }
        public Nullable<double> Numero1 { get; set; }
        public Nullable<double> Numero2 { get; set; }
        public Nullable<double> Numero3 { get; set; }
        public Nullable<double> Numero4 { get; set; }
        public Nullable<double> Numero5 { get; set; }
        public Nullable<double> Numero6 { get; set; }
        public Nullable<double> Numero7 { get; set; }
        public Nullable<double> Numero8 { get; set; }
        public Nullable<double> Numero9 { get; set; }
        public Nullable<double> Numero10 { get; set; }
        public string Texto1 { get; set; }
        public string Texto2 { get; set; }
        public string Texto3 { get; set; }
        public string Texto4 { get; set; }
        public string Texto5 { get; set; }
    }
}
