//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propuesta
    {
        public string EmprCod { get; set; }
        public string ProCodigo { get; set; }
        public string ProDesc { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<short> SucuCodigo { get; set; }
        public Nullable<System.DateTime> ProFechaIng { get; set; }
        public Nullable<System.DateTime> ProFechaPre { get; set; }
        public string ProEstadoAcep { get; set; }
        public string ProEstadoPro { get; set; }
        public Nullable<System.DateTime> ProFechaEstado { get; set; }
        public Nullable<short> ProResponsable { get; set; }
    }
}
