//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtosVenta
    {
        public short PtovCodigo { get; set; }
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string PtovNombre { get; set; }
        public string AlmaCodigo { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<double> ValmMonto { get; set; }
        public string PtovPath { get; set; }
        public Nullable<short> PtovFactura { get; set; }
        public Nullable<short> PtovBoleta { get; set; }
        public Nullable<short> PtovNVenta { get; set; }
        public Nullable<short> PtoNPagos { get; set; }
        public string PtovNSerieFiscal { get; set; }
        public string PtovNroPuerto { get; set; }
    }
}
