//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacCom
    {
        public string EmprCod { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<short> RelcCliente { get; set; }
        public Nullable<short> RelcProv { get; set; }
        public string RelcNombre { get; set; }
        public string RelcDirec { get; set; }
        public Nullable<short> ComuCodigo { get; set; }
        public Nullable<short> CiudCodigo { get; set; }
        public string RelcFono { get; set; }
        public string RelcFax { get; set; }
        public string RelcGiro { get; set; }
        public string RelcMail { get; set; }
        public Nullable<double> RelcDesc { get; set; }
        public Nullable<double> RelcCreMax { get; set; }
        public string ListCodigo { get; set; }
        public string RelcInfCom { get; set; }
        public Nullable<System.DateTime> RelcFechaPago { get; set; }
        public Nullable<System.DateTime> RelcFechaAnti { get; set; }
        public Nullable<double> RelcSobregiro { get; set; }
        public Nullable<double> RelcCoorX { get; set; }
        public Nullable<double> RelcCoorY { get; set; }
        public string RelcMapa { get; set; }
        public string RelcPagWEB { get; set; }
        public Nullable<int> RelcGraImport { get; set; }
        public Nullable<double> RelcPromedio { get; set; }
        public string RelcClasif { get; set; }
        public string RelcPersonaNombres { get; set; }
        public string RelcPersonaApellidoP { get; set; }
        public string RelcPersonaApellidoM { get; set; }
        public Nullable<short> RelcBloqueado { get; set; }
        public Nullable<short> RelcEmplCodigo2 { get; set; }
        public Nullable<short> RelcAsegurado { get; set; }
        public string RelcHolding { get; set; }
        public Nullable<double> RelcMontoCredito { get; set; }
        public string RelcSubClasif { get; set; }
        public Nullable<short> RelcEnvioCarta { get; set; }
    }
}
