//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reliquidacione
    {
        public string Emprcod { get; set; }
        public short RelAno { get; set; }
        public short Relmes { get; set; }
        public double RelNumero { get; set; }
        public Nullable<System.DateTime> RelFecha { get; set; }
        public Nullable<double> RelMomto { get; set; }
        public Nullable<System.DateTime> RelFechaInicio { get; set; }
        public Nullable<System.DateTime> RelFechaTermino { get; set; }
        public Nullable<int> RelTipo { get; set; }
        public Nullable<double> RelSueldoMin { get; set; }
        public string HDCodigo { get; set; }
    }
}
