//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public string repoSistema { get; set; }
        public int repoIndice { get; set; }
        public Nullable<short> repoTitulo { get; set; }
        public string repoNombre { get; set; }
        public string repoNombreCorto { get; set; }
        public Nullable<int> repoIndicePadre { get; set; }
        public Nullable<short> repoReporte { get; set; }
        public Nullable<int> repoOrden { get; set; }
        public string repoide { get; set; }
        public string repodesc { get; set; }
    }
}
