//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesOT
    {
        public string rootTipo { get; set; }
        public string rootRut { get; set; }
        public short rootExtranjero { get; set; }
        public string EmprCod { get; set; }
        public int OrtrNumero { get; set; }
        public double OrtrCodigo { get; set; }
        public int OrtrAno { get; set; }
    }
}
