//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sectore
    {
        public string EmprCod { get; set; }
        public string sectCodigo { get; set; }
        public string sectNombre { get; set; }
        public Nullable<double> sectPosX { get; set; }
        public Nullable<double> sectPosY { get; set; }
        public Nullable<double> sectAlto { get; set; }
        public Nullable<double> sectAncho { get; set; }
        public string nivelCod { get; set; }
    }
}
