//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        public string EdifCod { get; set; }
        public string TorrCodigo { get; set; }
        public string InmuCodigo { get; set; }
        public double SeguCorrel { get; set; }
        public string SeguTipo { get; set; }
        public Nullable<System.DateTime> SeguFechaIni { get; set; }
        public Nullable<System.DateTime> SeguFechaTer { get; set; }
        public string SeguInstitucion { get; set; }
        public string SeguPoliza { get; set; }
        public Nullable<double> SeguMonto { get; set; }
    }
}
