//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemaforoFilter
    {
        public int OP { get; set; }
        public string etapa { get; set; }
        public string OC { get; set; }
        public string Rut_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public double Codigo_Sucursal { get; set; }
        public string Nombre_Sucursal { get; set; }
        public string Codigo_Ruta { get; set; }
        public string Nombre_Ruta { get; set; }
        public string Codigo_Zona { get; set; }
        public string Nombre_Zona { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Despacho { get; set; }
        public string KAM { get; set; }
    }
}
