//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_TECNICO
    {
        public string Empresa { get; set; }
        public System.DateTime Fecha_OT { get; set; }
        public double Numero_OT { get; set; }
        public string Rut_Cliente { get; set; }
        public string Cliente_Final { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Tipo_Servicio { get; set; }
        public string Observacion_OT { get; set; }
        public string Descripcion_fallas { get; set; }
        public string Contacto { get; set; }
        public string Estado_OT { get; set; }
        public Nullable<int> Lugar_Servicio { get; set; }
        public string Descripcion_equipo { get; set; }
        public short Sucursal_cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Garantia { get; set; }
        public string Notas_Reparacion { get; set; }
        public string Direccion_Cliente { get; set; }
        public string Producto { get; set; }
        public string Numero_Serie { get; set; }
        public Nullable<System.DateTime> Fecha_asignacion_tecnico { get; set; }
        public string Nombre_Tecnico { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Tarea { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Tarea { get; set; }
        public string Estado_Tarea { get; set; }
        public Nullable<System.DateTime> Hora_Inicio_Tarea { get; set; }
        public Nullable<System.DateTime> Hora_Termino_Tarea { get; set; }
        public string Comentario_Tarea { get; set; }
        public Nullable<int> Correlativo_Presupuesto { get; set; }
        public string Estado_Presupuesto { get; set; }
        public string Presupuesto_Aceptado { get; set; }
        public Nullable<double> Gastos_Adicionales_Presupuesto { get; set; }
        public Nullable<double> Monto_Presupuesto { get; set; }
        public Nullable<System.DateTime> Fecha_Aceptacion_Presupuesto { get; set; }
        public string Observacion_Presupuesto { get; set; }
        public Nullable<double> Monto_Aceptado_Presupuesto { get; set; }
        public Nullable<System.DateTime> Fecha_Presupuesto { get; set; }
        public Nullable<double> Monto_ManoObra { get; set; }
        public Nullable<double> Monto_Repuestos { get; set; }
        public Nullable<double> CostoTotal_OT { get; set; }
        public Nullable<System.DateTime> Fecha_Facturacion { get; set; }
        public Nullable<double> Numero_Factura { get; set; }
    }
}
