//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInicial
    {
        public string AlmaCodigo { get; set; }
        public string EmprCod { get; set; }
        public short AlmaAno { get; set; }
        public short AlmaMes { get; set; }
        public double SiniNumero { get; set; }
        public Nullable<System.DateTime> SiniFecha { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<short> EmplCodigoAutoriza { get; set; }
        public Nullable<short> EmplCodigoModifica { get; set; }
        public Nullable<short> SiniGenSistema { get; set; }
    }
}
