//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucCom_2
    {
        public double SuccCodigo { get; set; }
        public string EmprCod { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public string SuccNombre { get; set; }
        public string SuccDirec { get; set; }
        public string SuccFono { get; set; }
        public string SuccFax { get; set; }
        public string SuccMail { get; set; }
        public Nullable<short> ComuCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public Nullable<double> RelcCoorX { get; set; }
        public Nullable<double> RelcCoorY { get; set; }
        public string RelcMapa { get; set; }
        public string RelcPagWEB { get; set; }
        public Nullable<short> regiCodigo { get; set; }
        public Nullable<short> CiudCodigo { get; set; }
        public string PaisCodigo { get; set; }
        public string SuccZonaG { get; set; }
        public string SuccRuta { get; set; }
        public Nullable<short> EmplCodigo2 { get; set; }
    }
}
