//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursale
    {
        public string SucuCodigo { get; set; }
        public string EmprCod { get; set; }
        public Nullable<double> SucPorVta { get; set; }
        public Nullable<double> SucGanancia { get; set; }
        public string SucuNombre { get; set; }
        public string SucuDirec { get; set; }
        public Nullable<short> ComuCodigo { get; set; }
        public string SucuFono { get; set; }
        public string SucuFax { get; set; }
        public string SucuMail { get; set; }
        public string SucuCodArea { get; set; }
        public Nullable<double> SucuCoorX { get; set; }
        public Nullable<double> SucuCoorY { get; set; }
        public string SucuMapa { get; set; }
        public Nullable<short> EmplCodigoJefeSuc { get; set; }
        public Nullable<int> SucuNroEmp { get; set; }
        public Nullable<short> SucuCasaMatriz { get; set; }
    }
}
