//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaConsulta
    {
        public string EmprCod { get; set; }
        public int TCNumCons { get; set; }
        public string TCNombreCons { get; set; }
        public System.DateTime TCFechaCons { get; set; }
        public string TCUsuario { get; set; }
    }
}
