//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TamanoTabla
    {
        public int id { get; set; }
        public string name { get; set; }
        public string rows { get; set; }
        public string reserved { get; set; }
        public string data { get; set; }
        public string index_size { get; set; }
        public string unused { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
