//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasOT
    {
        public string EmprCod { get; set; }
        public int OrtrNumero { get; set; }
        public int OtliCorrelativo { get; set; }
        public string ProdCodigo { get; set; }
        public int EmplCodigo { get; set; }
        public double OrtrCodigo { get; set; }
        public int OrtrAno { get; set; }
        public Nullable<System.DateTime> tareInicio { get; set; }
        public Nullable<System.DateTime> tareFin { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public Nullable<int> tareTipo { get; set; }
    }
}
