//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public string TarCodigo { get; set; }
        public string TarNombre { get; set; }
        public Nullable<short> TarTipo { get; set; }
        public Nullable<short> TarTipoMov { get; set; }
        public string InstCodigo { get; set; }
        public Nullable<double> TarPorcDesc { get; set; }
    }
}
