//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasaCotización
    {
        public string EmprCod { get; set; }
        public short TacotAno { get; set; }
        public short TacotMes { get; set; }
        public string InprCodigo { get; set; }
        public Nullable<double> TaCotTazaCotizacion { get; set; }
        public Nullable<double> TaCotTasaCotizacion { get; set; }
    }
}
