//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_desarrolloInveValAgrupStockLotes
    {
        public string CodEmpresa { get; set; }
        public Nullable<int> Agno { get; set; }
        public Nullable<int> Mes { get; set; }
        public string UniMed { get; set; }
        public string RutCli_Prov { get; set; }
        public short CliExtranjero { get; set; }
        public string SucEmpresa { get; set; }
        public double OrdenNumero { get; set; }
        public string Documento { get; set; }
        public string CodProducto { get; set; }
        public string DescProducto { get; set; }
        public string TipDocumento { get; set; }
        public short OrdenMovimiento { get; set; }
        public string CodAlmacen { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> FechIngreso { get; set; }
        public Nullable<System.DateTime> FechVencimiento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string RelcNombre { get; set; }
    }
}
