//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPresupuesto
    {
        public string EmprCod { get; set; }
        public string TipeCodigo { get; set; }
        public string TipeNombre { get; set; }
        public Nullable<int> TipeTipoPeriodo { get; set; }
        public Nullable<int> TipoNumeroPeriodos { get; set; }
    }
}
