//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPago
    {
        public string TpagCodigo { get; set; }
        public string EmprCod { get; set; }
        public short TpagAno { get; set; }
        public string TpagNombre { get; set; }
        public Nullable<short> TpagTrat { get; set; }
        public string CtaCCodigo { get; set; }
        public Nullable<short> TpagMov { get; set; }
        public Nullable<short> TpagReqIdent { get; set; }
        public Nullable<short> TpagConVuelto { get; set; }
        public string RelcRut { get; set; }
        public Nullable<short> RelcExtranjero { get; set; }
        public string TpagEmprCodFinan { get; set; }
        public Nullable<double> TpagTasaFinan { get; set; }
        public string TpagCodigoEnFinan { get; set; }
        public string TdocCodigo { get; set; }
        public string ProdCodigoFinan { get; set; }
        public Nullable<short> PtovCodigo { get; set; }
        public Nullable<int> TpagCantMesesPC { get; set; }
    }
}
