//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposConversion
    {
        public string EmprCod { get; set; }
        public short TicoAno { get; set; }
        public string TicoCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public double TiCoCorrelativo { get; set; }
        public string ProdCodList { get; set; }
        public string TicoDescripcion { get; set; }
        public Nullable<double> TicoCantidadProd { get; set; }
        public Nullable<int> TicoTipo { get; set; }
        public string TicoCategoria { get; set; }
    }
}
