//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajosImpresion
    {
        public int TAIMCodigo { get; set; }
        public int ImpreCodigo { get; set; }
        public string TaImWhere { get; set; }
        public string TaImNomTabla { get; set; }
    }
}
