//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraspLinea
    {
        public double TrasNumero { get; set; }
        public string AlmaCodigOri { get; set; }
        public string AlmaCodigoDes { get; set; }
        public string EmprCod { get; set; }
        public short TlinAno { get; set; }
        public string ProdCodigo { get; set; }
        public double TlinCorrel { get; set; }
        public Nullable<short> TlinMes { get; set; }
        public Nullable<double> TlinNeto { get; set; }
        public Nullable<double> TlinBruto { get; set; }
        public Nullable<double> TlinCantidad { get; set; }
        public Nullable<double> TlinTotalLinea { get; set; }
    }
}
