//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traza
    {
        public int ID { get; set; }
        public Nullable<int> IDEtapa { get; set; }
        public Nullable<System.DateTime> HIni { get; set; }
        public Nullable<System.DateTime> HTer { get; set; }
        public Nullable<bool> Term { get; set; }
    }
}
