//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public string EmprCod { get; set; }
        public short TurCodigo { get; set; }
        public int TurDia { get; set; }
        public string TurDescripcion { get; set; }
        public Nullable<System.DateTime> TurHoraIni { get; set; }
        public Nullable<System.DateTime> TurHoraFin { get; set; }
        public Nullable<System.DateTime> TurColacion { get; set; }
    }
}
