//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnosEmpleado
    {
        public string EmprCod { get; set; }
        public short TurCodigo { get; set; }
        public int HabDesAno { get; set; }
        public int HabDesMes { get; set; }
        public System.DateTime TurFechaDesde { get; set; }
        public System.DateTime TurFechaHasta { get; set; }
        public string EmplRut { get; set; }
    }
}
