//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNILEVER_FLUJO
    {
        public int ID { get; set; }
        public string Customer_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> Dummy_RAD { get; set; }
        public string Item_Category { get; set; }
        public string Material_UCC14 { get; set; }
        public string Material_DU { get; set; }
        public string Material_Description { get; set; }
        public string Delivery_Note { get; set; }
        public string Shipment_Number { get; set; }
        public string Order_Quantity { get; set; }
        public string UoM { get; set; }
        public string Delivery_Note_Quantity { get; set; }
        public string Credit_Status { get; set; }
        public string Actual_Goods_Issue_Date { get; set; }
        public string Delivery_Creation { get; set; }
        public string Invoice_Number { get; set; }
        public string Billing_Date { get; set; }
        public string Billing_Net_Value { get; set; }
        public string Reference_Document_Number { get; set; }
        public string Billing_Quantity { get; set; }
        public string FECHA_DE_hr { get; set; }
        public string fecha_de_agendamiento_ { get; set; }
        public string hora_de_agendamiento { get; set; }
        public string Cantidad_a_despachar { get; set; }
        public string Customer_Purchase_Or { get; set; }
        public string Ship_To { get; set; }
        public Nullable<System.DateTime> PO_Date { get; set; }
        public string Sales_Order_Number { get; set; }
        public short procesado { get; set; }
    }
}
