//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_web
    {
        public int usme_id { get; set; }
        public string usme_usuario { get; set; }
        public string usme_contrasena { get; set; }
        public string usme_nombre { get; set; }
        public Nullable<int> usme_tipo { get; set; }
        public string usme_contrasenaORG { get; set; }
        public string usme_codigo { get; set; }
        public Nullable<int> camaras { get; set; }
        public string usme_rut { get; set; }
    }
}
