//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empleados_registra
    {
        public int EmplCodigo { get; set; }
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public string EmplDigito { get; set; }
        public string EmplNombre { get; set; }
        public string EmplApellidoP { get; set; }
        public string EmplApellidoM { get; set; }
        public Nullable<short> EmplVend { get; set; }
        public Nullable<short> EmplCaja { get; set; }
        public Nullable<int> EmplComuna { get; set; }
        public string EmplDirecc { get; set; }
        public Nullable<short> EmplInv { get; set; }
        public string SucuCodigo { get; set; }
        public byte[] EmplFoto { get; set; }
        public string EmplNomFoto { get; set; }
        public Nullable<short> EmplConfianza { get; set; }
        public Nullable<short> EmplDecCompra { get; set; }
        public Nullable<short> EmplSupervisor { get; set; }
        public string EmplRutF { get; set; }
        public Nullable<short> EmplExtranjero { get; set; }
        public string EmplProfesion { get; set; }
        public Nullable<System.DateTime> EmplFechaNac { get; set; }
        public Nullable<short> EmplSexo { get; set; }
        public Nullable<short> EmplEstadoCivil { get; set; }
        public string EmplLlamarAU { get; set; }
        public Nullable<int> EmplFonoU { get; set; }
        public string EmplCalleU { get; set; }
        public string EmplNumeroU { get; set; }
        public string EmplDeptoU { get; set; }
        public Nullable<int> EmplCiudadU { get; set; }
        public Nullable<int> EmplRegionU { get; set; }
        public Nullable<int> EmplComunaU { get; set; }
    }
}
