//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValMulAtributoDocumento
    {
        public string EmprCod { get; set; }
        public string ProyCodigo { get; set; }
        public string MandCodigo { get; set; }
        public string EtapCodigo { get; set; }
        public int FormNumero { get; set; }
        public int VaadNUB { get; set; }
        public int VaadIndice { get; set; }
        public string DCTLNN00 { get; set; }
        public string DCTLNN01 { get; set; }
        public string DCTLNN02 { get; set; }
        public string DCTLNN03 { get; set; }
        public string DCTLNN04 { get; set; }
        public string DCTLNN05 { get; set; }
        public string DCTLNN06 { get; set; }
        public string DCTLNN07 { get; set; }
        public string DCTLNN08 { get; set; }
        public string DCTLNN09 { get; set; }
        public string DCTLNN10 { get; set; }
        public string DCTLNN11 { get; set; }
        public string DCTLNN12 { get; set; }
        public string DCTLNN13 { get; set; }
        public string DCTLNN14 { get; set; }
        public string DCTLNN15 { get; set; }
        public string DCTLNN16 { get; set; }
        public string DCTLNN17 { get; set; }
        public string DCTLNN18 { get; set; }
        public string DCTLNN19 { get; set; }
    }
}
