//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresAtributoDocumento
    {
        public string EmprCod { get; set; }
        public string ProyCodigo { get; set; }
        public string MandCodigo { get; set; }
        public string EtapCodigo { get; set; }
        public int FormNumero { get; set; }
        public string DCTLNC00 { get; set; }
        public string DCTLNC01 { get; set; }
        public string DCTLNC02 { get; set; }
        public string DCTLNC03 { get; set; }
        public string DCTLNC04 { get; set; }
        public string DCTLNC05 { get; set; }
        public string DCTLNC06 { get; set; }
        public string DCTLNC07 { get; set; }
        public string DCTLNC08 { get; set; }
        public string DCTLNC09 { get; set; }
        public string DCTLNC10 { get; set; }
        public string DCTLNC11 { get; set; }
        public string DCTLNC12 { get; set; }
        public string DCTLNC13 { get; set; }
        public string DCTLNC14 { get; set; }
        public string DCTLNC15 { get; set; }
        public string DCTLNC16 { get; set; }
        public string DCTLNC17 { get; set; }
        public string DCTLNC18 { get; set; }
        public string DCTLNC19 { get; set; }
        public string DCTLNC20 { get; set; }
        public string DCTLNC21 { get; set; }
        public string DCTLNC22 { get; set; }
        public string DCTLNC23 { get; set; }
        public string DCTLNC24 { get; set; }
        public string DCTLNC25 { get; set; }
        public string DCTLNC26 { get; set; }
        public string DCTLNC27 { get; set; }
        public string DCTLNC28 { get; set; }
        public string DCTLNC29 { get; set; }
        public string DCTLNC30 { get; set; }
        public string DCTLNC31 { get; set; }
        public string DCTLNC32 { get; set; }
        public string DCTLNC33 { get; set; }
        public string DCTLNC34 { get; set; }
        public string DCTLNC35 { get; set; }
        public string DCTLNC36 { get; set; }
        public string DCTLNC37 { get; set; }
        public string DCTLNC38 { get; set; }
        public string DCTLNC39 { get; set; }
        public string DCTLCD00 { get; set; }
        public string DCTLCD01 { get; set; }
        public string DCTLCD02 { get; set; }
        public string DCTLCD03 { get; set; }
        public string DCTLCD04 { get; set; }
        public string DCTLCD05 { get; set; }
        public string DCTLCD06 { get; set; }
        public string DCTLCD07 { get; set; }
        public string DCTLCD08 { get; set; }
        public string DCTLCD09 { get; set; }
        public string DCTLCD10 { get; set; }
        public string DTEXTO00 { get; set; }
        public string DTEXTO01 { get; set; }
        public string DTEXTO02 { get; set; }
        public string DTEXTO03 { get; set; }
        public string DTEXTO04 { get; set; }
        public string DTEXTO05 { get; set; }
        public string DTEXTO06 { get; set; }
        public string DTEXTO07 { get; set; }
        public string DTEXTO08 { get; set; }
        public string DTEXTO09 { get; set; }
        public string DTEXTO10 { get; set; }
    }
}
