//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorKit
    {
        public string KitsCodigo { get; set; }
        public string ListCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ValKAno { get; set; }
        public Nullable<double> ValKNeto { get; set; }
        public Nullable<double> ValKBruto { get; set; }
        public Nullable<double> ValKMargenReal { get; set; }
        public Nullable<double> ValKSugerido { get; set; }
        public Nullable<short> ValKModificado { get; set; }
        public Nullable<System.DateTime> ValKFecha { get; set; }
        public string ValKUltRutCli { get; set; }
    }
}
