//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class versiones_ejecutadas
    {
        public string CosiSistema { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string version { get; set; }
        public string CosiLogin { get; set; }
        public string CosiComputerName { get; set; }
    }
}
