//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidaUtil
    {
        public string EmprCod { get; set; }
        public string RelcRut { get; set; }
        public string RelcExtranjero { get; set; }
        public string LproCodigo { get; set; }
        public short MproCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public string LproNombre { get; set; }
        public string MproNombre { get; set; }
        public Nullable<int> AgPorcRetenido { get; set; }
        public string ProdNombre { get; set; }
    }
}
