//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_RUTAS_AGRUPADO_CIUDAD
    {
        public string Empresa { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<double> Numero_HR { get; set; }
        public string ZONA { get; set; }
        public string CIUDAD_DESPACHO { get; set; }
        public Nullable<double> TotalKilos { get; set; }
        public Nullable<double> TotalNeto { get; set; }
        public Nullable<double> CapacidadT { get; set; }
        public string NomTransportista { get; set; }
        public string NomChofer { get; set; }
        public Nullable<int> CantFacturas { get; set; }
        public Nullable<double> ValorRuta { get; set; }
        public string NombreDia { get; set; }
        public Nullable<double> HoRuPalletAzul { get; set; }
        public Nullable<double> HoRuPalletBlanco { get; set; }
    }
}
