//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DATOS_LOGISTICOS
    {
        public string ProdCodigo { get; set; }
        public string EmprCod { get; set; }
        public short ProdAno { get; set; }
        public string ProdNombre { get; set; }
        public Nullable<short> ProdServ { get; set; }
        public Nullable<short> ProdCompras { get; set; }
        public Nullable<short> ProdVentas { get; set; }
        public string LproCodigo { get; set; }
        public string DeptCodigo { get; set; }
        public Nullable<double> ProdUPC { get; set; }
        public string ProdMedidaC { get; set; }
        public string ProdMedidaV { get; set; }
        public Nullable<double> ProdFactorC { get; set; }
        public Nullable<double> ProdStockTeo { get; set; }
        public Nullable<double> ProdPrecioC { get; set; }
        public Nullable<double> ProdCostoBase { get; set; }
        public Nullable<double> ProdFlete { get; set; }
        public Nullable<short> ProdEsLiquido { get; set; }
        public string ProdCtaCV { get; set; }
        public string ProdCtaCVHab { get; set; }
        public string ProdCtaCCVenta { get; set; }
        public string ProdCtaCCVentaHab { get; set; }
        public Nullable<short> ProdEsToxico { get; set; }
        public Nullable<short> ProdEsPerecible { get; set; }
        public Nullable<short> ProdImportado { get; set; }
        public Nullable<double> ProdCostoUnit { get; set; }
        public Nullable<double> ProdNCostoUnit { get; set; }
        public string ProdTipMCodigo { get; set; }
        public string ProdTipNMCodigo { get; set; }
        public Nullable<short> ProdCantDecCpa { get; set; }
        public Nullable<short> ProdCantDecVta { get; set; }
        public Nullable<System.DateTime> ProdFechaUCompra { get; set; }
        public Nullable<System.DateTime> ProdNFechaUCompra { get; set; }
        public Nullable<short> ProdDiasPerecibles { get; set; }
        public Nullable<short> ProdExportable { get; set; }
        public Nullable<short> ProdEsHortaliza { get; set; }
        public string CtaCExistencias { get; set; }
        public string CtaCExistenciasHab { get; set; }
        public string ProdCtaCCMPerdida { get; set; }
        public string ProdCtaCCMGanancia { get; set; }
        public string ProdCtaCCMPerdidaHab { get; set; }
        public string ProdCtaCCMGananciaHab { get; set; }
        public string GproCodigo { get; set; }
        public Nullable<short> MproCodigo { get; set; }
        public Nullable<double> ProdInvMinimo { get; set; }
        public Nullable<double> ProdInvMaximo { get; set; }
        public Nullable<short> ProdMetodoInv { get; set; }
        public string ProdNombreFoto { get; set; }
        public string ProdCtaGastos { get; set; }
        public string CodRCodigo { get; set; }
        public Nullable<double> ProdPrecioCBruto { get; set; }
        public Nullable<int> PproCodigo { get; set; }
        public Nullable<int> FproCodigo { get; set; }
        public string CODIGOS_EAN13 { get; set; }
        public string CODIGOS_DUN14 { get; set; }
        public Nullable<double> UNIDAD_ALTURA { get; set; }
        public Nullable<double> UNIDAD_ANCHOODIAMT { get; set; }
        public Nullable<double> UNIDAD_PESOTEORICO { get; set; }
        public Nullable<double> UNIDAD_PESO_bruto_kilos { get; set; }
        public Nullable<double> DATCAJ_UNIDADES { get; set; }
        public Nullable<double> DATCAJ_ALTURA { get; set; }
        public Nullable<double> DATCAJ_ANCHO_FONDO { get; set; }
        public Nullable<double> DATCAJ_PESOTEORICO { get; set; }
        public Nullable<double> DATCAJ_PESObrutokilos { get; set; }
        public string DATCAJ_DIFPESO { get; set; }
        public string DATCAJ_VOLUMEN { get; set; }
        public string DATCAJ_PESOVOL { get; set; }
        public string DATPALREC_UNI { get; set; }
        public string DATPALREC_BASE { get; set; }
        public string DATPALREC_ALT { get; set; }
        public string DATPALREC_CJS { get; set; }
        public string DATPALREC_PESONETO { get; set; }
        public string DATPALREC_PESObruto { get; set; }
        public string DATPALREC_MTCUB { get; set; }
        public string CDPRODEA_BASE { get; set; }
        public string CDPRODEA_ALT { get; set; }
        public string CDPRODEA_CJS { get; set; }
        public string CDPRODEA_CMSALT { get; set; }
        public string CDPRODEA_PESOKG { get; set; }
        public string DYS_CJS { get; set; }
        public string DYS_CMSALT { get; set; }
        public string CENCO_CJS { get; set; }
        public string CENCO_CMSALT { get; set; }
        public string MESVIDAUTIL { get; set; }
        public string DIASVIDAUTIL { get; set; }
        public string CAMION_CAJAS { get; set; }
        public string CAMION_PALLET { get; set; }
        public string CAMION_PESOTEORICO { get; set; }
        public string CODIGO_EAN13_DISPLAY { get; set; }
        public string CODIGO_PROVEEDOR { get; set; }
        public string UNIDAD_FONDO { get; set; }
        public string UNIDAD_TIPO_ENVASE { get; set; }
        public string DATCAJ_FONDO { get; set; }
        public string DATCAJ_STOCK_CAJA { get; set; }
        public string DATPALREC_ALTURA { get; set; }
        public string DYS_BASE { get; set; }
        public string DYS_ALT { get; set; }
        public string CENCO_BASE { get; set; }
        public string CENCO_ALT { get; set; }
        public string CAMION_PESOBRUTO { get; set; }
    }
}
