//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_CONTRATOS
    {
        public string EmprCod { get; set; }
        public string EmplRut { get; set; }
        public short EmplExtranjero { get; set; }
        public short ContAno { get; set; }
        public short ContMes { get; set; }
        public int MovMenCorrel { get; set; }
        public string ContNacionalidad { get; set; }
        public string ContEstadoCivil { get; set; }
        public string ContDomicilio { get; set; }
        public string ContLabor { get; set; }
        public string ContLugar { get; set; }
        public string ContHorario { get; set; }
        public string ContBeneficios { get; set; }
        public string ContDuracion { get; set; }
        public Nullable<System.DateTime> ContFechaEmision { get; set; }
        public string ContProcedencia { get; set; }
        public string ContArea { get; set; }
        public string ContLocalizacion { get; set; }
        public Nullable<short> ContTipoPago { get; set; }
        public string ContRemuAdicional { get; set; }
        public string ContGratificacion { get; set; }
        public string ContModelo { get; set; }
        public string Apellido_P { get; set; }
        public string Apellido_M { get; set; }
        public string Nombre { get; set; }
    }
}
