//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_PRELIBRO_COMPRA
    {
        public string EmprCod { get; set; }
        public string SucuCodigo { get; set; }
        public string TdocCodigo { get; set; }
        public short OdocMovimiento { get; set; }
        public double OdocNumero { get; set; }
        public string RelcRut { get; set; }
        public short RelcExtranjero { get; set; }
        public Nullable<short> OdocAno { get; set; }
        public Nullable<short> OdocMes { get; set; }
        public Nullable<System.DateTime> OdocFechaI { get; set; }
        public Nullable<System.DateTime> OdocFechaV { get; set; }
        public string AlmaCodigo { get; set; }
        public Nullable<double> SuccCodigo { get; set; }
        public string ListCodigo { get; set; }
        public Nullable<short> ContCodigo { get; set; }
        public Nullable<short> EmplCodigo { get; set; }
        public string TipmCodigo { get; set; }
        public Nullable<double> OdocTipmMonto { get; set; }
        public Nullable<short> OdocExenta { get; set; }
        public Nullable<double> OdocAfecto { get; set; }
        public Nullable<double> OdocExento { get; set; }
        public Nullable<double> OdocTerreno { get; set; }
        public string OdocObservacion { get; set; }
        public Nullable<double> OdocSubTotal { get; set; }
        public Nullable<double> OdocTotal { get; set; }
        public Nullable<double> OdocNumImpre { get; set; }
        public string OdocDesFPago { get; set; }
        public string OdocOC { get; set; }
        public Nullable<int> OdocEstado { get; set; }
        public string TpagCodigo { get; set; }
        public Nullable<double> FPCPCorrel { get; set; }
        public Nullable<double> OdocSaldo { get; set; }
        public Nullable<short> OdocCuotas { get; set; }
        public Nullable<short> OdocNulo { get; set; }
        public Nullable<short> odocaprobada { get; set; }
        public Nullable<System.DateTime> OdocFechaDespacho { get; set; }
        public string OdocNroOC { get; set; }
        public Nullable<short> OdocAgenda { get; set; }
        public Nullable<int> OdocDestino { get; set; }
        public Nullable<System.DateTime> OdocFechaProgramada { get; set; }
        public string OdocGlosa1 { get; set; }
        public string OdocGlosa2 { get; set; }
        public string OdocGlosa3 { get; set; }
        public Nullable<System.DateTime> OdocFecIniArmado { get; set; }
        public Nullable<short> OdocPendientes { get; set; }
        public Nullable<short> OdocEsperaKilos { get; set; }
    }
}
