//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_CONTABILIDAD_EMP_13
    {
        public string Empresa { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nulo { get; set; }
        public int NroVoucher { get; set; }
        public int LineaNro { get; set; }
        public string GlosaLinea { get; set; }
        public string Cuenta { get; set; }
        public string ClasifCuenta { get; set; }
        public string CodCtroRes { get; set; }
        public string NomCtroRes { get; set; }
        public Nullable<double> Monto { get; set; }
        public string CodTipoDocto { get; set; }
        public string NomTipoDocto { get; set; }
        public Nullable<double> NroDocumento { get; set; }
        public string Rut { get; set; }
        public string Extranjero { get; set; }
        public Nullable<System.DateTime> VctoDocto { get; set; }
        public string TipoCuenta { get; set; }
        public string NomCuenta { get; set; }
        public string NomRut { get; set; }
    }
}
