//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_RELOJ_CONTROL_20180117
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public string FINIQUITADO { get; set; }
        public string MOVIMIENTO { get; set; }
        public string RUT { get; set; }
        public string N_TRABAJADOR { get; set; }
        public string AREA { get; set; }
        public Nullable<System.DateTime> HORA_EXTRAS { get; set; }
        public string DEPARTAMENTO { get; set; }
    }
}
