//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_RELOJ_ASISTENCIA_TURNOS_2
    {
        public string Rut { get; set; }
        public string NomEmpleado { get; set; }
        public string Movimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Area { get; set; }
        public string CentroCosto { get; set; }
        public string DEPARTAMENTO { get; set; }
        public Nullable<int> MINUTOS_EXTRA { get; set; }
        public Nullable<int> MINUTOS_ATRASOS { get; set; }
        public Nullable<int> MINUTOS_PERMISO { get; set; }
        public string MOTIVO_PERMISO { get; set; }
        public string SE_DESCUENTA { get; set; }
        public string DIA_SEMANA { get; set; }
        public string DIA_HABIL { get; set; }
        public string Turno { get; set; }
    }
}
