//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Log_Web
    {
        public string Página { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Departamento { get; set; }
        public Nullable<System.DateTime> Fecha_Acceso { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
    }
}
