//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ABASTECIMIENTO_NUEVA
    {
        public string Empresa { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> Mes { get; set; }
        public Nullable<short> Tipo_Movimiento { get; set; }
        public Nullable<double> Numero { get; set; }
        public string Rut { get; set; }
        public Nullable<short> Extranjero { get; set; }
        public string Nombre_CliProv { get; set; }
        public Nullable<short> CodVendedor { get; set; }
        public string NomVendedor { get; set; }
        public string Cod_Producto { get; set; }
        public string Nom_Producto { get; set; }
        public string LineaProducto { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<double> Cajas { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<double> PrecioUnitarioNeto { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public Nullable<double> PrecioNetoTotFinal { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> CantPendiente { get; set; }
        public Nullable<double> CajasPendientes { get; set; }
        public Nullable<double> VentaPendiente { get; set; }
        public Nullable<double> NroSemana { get; set; }
        public string TipoDoc { get; set; }
        public Nullable<double> OC { get; set; }
        public Nullable<double> DP { get; set; }
        public Nullable<double> PF { get; set; }
        public Nullable<double> GD { get; set; }
        public string Producto { get; set; }
        public Nullable<double> OC_S1 { get; set; }
        public Nullable<double> OC_S2 { get; set; }
        public Nullable<double> OC_S3 { get; set; }
        public Nullable<double> OC_S4 { get; set; }
        public Nullable<double> OC_S5 { get; set; }
        public Nullable<double> DP_S1 { get; set; }
        public Nullable<double> DP_S2 { get; set; }
        public Nullable<double> DP_S3 { get; set; }
        public Nullable<double> DP_S4 { get; set; }
        public Nullable<double> DP_S5 { get; set; }
        public Nullable<double> PF_S1 { get; set; }
        public Nullable<double> PF_S2 { get; set; }
        public Nullable<double> PF_S3 { get; set; }
        public Nullable<double> PF_S4 { get; set; }
        public Nullable<double> PF_S5 { get; set; }
        public Nullable<double> GD_S1 { get; set; }
        public Nullable<double> GD_S2 { get; set; }
        public Nullable<double> GD_S3 { get; set; }
        public Nullable<double> GD_S4 { get; set; }
        public Nullable<double> GD_S5 { get; set; }
        public string ORDEN { get; set; }
        public Nullable<double> Total_OC { get; set; }
        public Nullable<double> Total_DP { get; set; }
        public Nullable<double> Total_PF { get; set; }
        public Nullable<double> Total_GD { get; set; }
        public Nullable<double> Saldo_OC { get; set; }
        public Nullable<double> Saldo_DP { get; set; }
        public Nullable<double> Saldo_PF { get; set; }
    }
}
