//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ARCHITEQ_PERSONAS
    {
        public string RUT { get; set; }
        public string DV { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string EmprPaterno { get; set; }
        public string Departamento { get; set; }
        public int estado { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> FechaCaducidadContrato { get; set; }
        public string PATENTES { get; set; }
        public int EmplCodigo { get; set; }
    }
}
