//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ARCHITEQ_TURNOS
    {
        public string Empresa { get; set; }
        public string llave { get; set; }
        public string TurDescripcion { get; set; }
        public string entrada { get; set; }
        public string salida { get; set; }
        public string colacion { get; set; }
    }
}
