//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BANCO_BICE
    {
        public string EmpleadoNombre { get; set; }
        public string Rut { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<int> CodigoBanco { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public Nullable<int> Moneda { get; set; }
        public int OficinaOrigen { get; set; }
        public int OficinaDestino { get; set; }
        public short Mes { get; set; }
        public string Empresa { get; set; }
        public Nullable<double> Anticipo { get; set; }
    }
}
