//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CostoLinea
    {
        public int Año { get; set; }
        public string LproNombre { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<int> mes { get; set; }
    }
}
