//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOCTO_PENDIENTES
    {
        public string Codigo { get; set; }
        public Nullable<short> Posicion { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> CantidadEntregada { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Moneda { get; set; }
        public int Incoterm { get; set; }
        public string Proveedor { get; set; }
        public string CodigoAnterior { get; set; }
        public string PosicionAnterior { get; set; }
        public string TipoDocto { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public string NombreTipoDocto { get; set; }
    }
}
