//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DESCUENTOS
    {
        public string Empresa { get; set; }
        public short Año { get; set; }
        public short Mes { get; set; }
        public string Rut { get; set; }
        public string Apellido_P { get; set; }
        public string Apellido_M { get; set; }
        public string Nombre { get; set; }
        public string TIPO_HABER_DESCUENTO { get; set; }
        public string CentroCosto { get; set; }
        public string DEPARTAMENTO { get; set; }
        public Nullable<double> AHORRO_HABITACIONAL { get; set; }
        public Nullable<double> DESCUENTO_TAG { get; set; }
        public Nullable<double> ANTICIPO_EXTRAORDINARIO { get; set; }
        public Nullable<double> COMPRA_LEASING { get; set; }
        public Nullable<double> CONVENIO_DENTAL { get; set; }
        public Nullable<double> DONACION { get; set; }
        public Nullable<double> FACTURAS { get; set; }
        public Nullable<double> GIMNASIO_ENERGY { get; set; }
        public Nullable<double> GIMNASIO_PACIFIC { get; set; }
        public Nullable<double> OPTICA { get; set; }
        public Nullable<double> OTRO_DESCUENTO { get; set; }
        public Nullable<double> OTROS_DESCUENTOS { get; set; }
        public Nullable<double> PRESTAMO_BCO__CHILE { get; set; }
        public Nullable<double> PRESTAMO_CAJA_LOS_ANDES { get; set; }
        public Nullable<double> PRESTAMO_EMPRESA__1_ { get; set; }
        public Nullable<double> PRESTAMO_EMPRESA__2_ { get; set; }
        public Nullable<double> SALCOBRAND { get; set; }
        public Nullable<double> SEGURO_COMPLEMENTARIO { get; set; }
        public Nullable<double> TELEFONO { get; set; }
        public Nullable<double> UNIFORMES { get; set; }
        public Nullable<double> VENTA_DE_BODEGA { get; set; }
    }
}
