//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KPI2
    {
        public string RelcRut { get; set; }
        public string TdocCodigo { get; set; }
        public string ProdCodigo { get; set; }
        public Nullable<double> OdliCantidad { get; set; }
        public Nullable<double> Cantidad_Cajas { get; set; }
        public double OdocNumero { get; set; }
        public Nullable<System.DateTime> OdocFechaI { get; set; }
    }
}
