//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ML_Pedidos
    {
        public int MLPid { get; set; }
        public Nullable<int> MLPnroPedido { get; set; }
        public string MLPEstado { get; set; }
        public int LogId { get; set; }
        public string LogDocumento { get; set; }
        public string LogInfo { get; set; }
        public Nullable<System.DateTime> LogFecha { get; set; }
        public string LogEstadoDoc { get; set; }
        public string LogTipoDoc { get; set; }
        public Nullable<System.TimeSpan> LogHora { get; set; }
    }
}
