//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OD_DOCT
    {
        public string Rut { get; set; }
        public string TD { get; set; }
        public double NroDoct { get; set; }
        public string RazonSocial { get; set; }
        public string Sucursal { get; set; }
        public double Cod_Suc { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public double NumOP { get; set; }
        public short Extrajero { get; set; }
        public string TdocCodigo { get; set; }
        public short Movimiento { get; set; }
    }
}
