//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SaldoVacaciones
    {
        public string Rut { get; set; }
        public string NombreEmpleado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaIniUlt { get; set; }
        public Nullable<System.DateTime> FechaFinUlt { get; set; }
        public Nullable<double> TotalDias { get; set; }
        public Nullable<double> DiasTomados { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> Diasprogresivos { get; set; }
        public short Año { get; set; }
        public string Empresa { get; set; }
        public short Mes { get; set; }
    }
}
