//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALANA_CargasFamiliares
    {
        public short Año { get; set; }
        public short Mes { get; set; }
        public string RutTrabajador { get; set; }
        public string Relacion { get; set; }
        public string Rut_Carga { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Sexo { get; set; }
        public string EsCarga { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Observaciones { get; set; }
    }
}
