//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALANA_Vacaciones
    {
        public string Tipo { get; set; }
        public string emplrut { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> DetVaTotalDias { get; set; }
        public Nullable<double> DetVaDiasProgresivos { get; set; }
        public string obs { get; set; }
    }
}
