//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Talana_Empleados
    {
        public short mes { get; set; }
        public short año { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string rut { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Sexo { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string email_personal { get; set; }
        public string password { get; set; }
        public string Celular { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string TipoContrato { get; set; }
        public string Profesion { get; set; }
        public string Estado_Civil { get; set; }
        public string observaciones { get; set; }
        public string NIVEL_EDUCACIONAL { get; set; }
        public string contactoEmergencia { get; set; }
        public string Direccion { get; set; }
        public string Numero_Direccion { get; set; }
        public string Dpto { get; set; }
        public string Comuna { get; set; }
        public string Ciudad { get; set; }
        public string Razon_Social_Empleado { get; set; }
        public string Cargo { get; set; }
        public string Fecha_Inicio { get; set; }
        public string Fecha_Finiquito { get; set; }
        public string Motivo_Egreso { get; set; }
        public string Jornada { get; set; }
        public Nullable<short> Jornada_Laboral { get; set; }
        public string Jefe { get; set; }
        public string Cod_Centro_Costo { get; set; }
        public string Centro_Costo { get; set; }
        public string Sindicato { get; set; }
        public string Cod_unidadOrganizacional { get; set; }
        public string unidadOrganizacional { get; set; }
        public string Sucursal { get; set; }
        public string AFP { get; set; }
        public string ISAPRE { get; set; }
        public string Monto_Pactado_Isapre { get; set; }
        public Nullable<double> Valor_Monto_Isapre { get; set; }
        public Nullable<double> Valor_Monto_Isapre2 { get; set; }
        public string Es_Pensionado { get; set; }
        public Nullable<int> Meses_Imponibles_Reconocido { get; set; }
        public string TramoAsignacionPrevisional { get; set; }
        public string APV { get; set; }
        public string TipoPago { get; set; }
        public Nullable<double> Sueldo_Base { get; set; }
        public Nullable<double> Movilizacion { get; set; }
        public Nullable<int> Colacion { get; set; }
        public string FormaPago { get; set; }
        public string TipoCuenta { get; set; }
        public string BANCO { get; set; }
        public string Nro_Cuenta_bancaria { get; set; }
        public string Institucion_APV { get; set; }
        public Nullable<double> Monto_APV { get; set; }
        public string Tipo_APV { get; set; }
        public string Moneda_APV { get; set; }
        public string permisos { get; set; }
        public Nullable<int> codigo { get; set; }
        public string anexo { get; set; }
        public string Cod_FranquiciaSence { get; set; }
        public string nivelSence { get; set; }
        public string INE { get; set; }
        public string pagaTresPrimerosDiasdeLicencia { get; set; }
        public string mantieneRetaliquidaLicencia { get; set; }
        public string diasAdministrativo { get; set; }
        public string beneficioInfoAdicional { get; set; }
        public string valorHoraExtraPactada { get; set; }
        public string diasAdicionalesVacaciones { get; set; }
        public string adscribeASeguroCesantiaParaContratosPreviosA2002 { get; set; }
        public string fechaSeguroCesantiaParaContratosPreviosA2002 { get; set; }
        public int trabajoPesadoPorcentaje { get; set; }
        public Nullable<short> asignacionZonaExtrema { get; set; }
        public string fechaDeContratacionReconocidaParaAnosDeServicio { get; set; }
        public string rolPrivado { get; set; }
        public string grupos { get; set; }
        public string claseSalarial { get; set; }
        public Nullable<double> Anticipo_Pactado { get; set; }
        public Nullable<System.DateTime> VacacionesReconocidasDesde { get; set; }
    }
}
