//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALANA_HaberesYDescuentosHistorico
    {
        public string EmplRut { get; set; }
        public Nullable<int> AnoMes { get; set; }
        public Nullable<double> MovMenSdoBaseGanado { get; set; }
        public Nullable<int> DiasTrabajados { get; set; }
        public Nullable<double> MovMenTotImponible { get; set; }
        public Nullable<double> MovMenTotalNoImponoble { get; set; }
        public Nullable<double> MovMenTotHaber { get; set; }
        public Nullable<double> DescuentosLegales { get; set; }
        public Nullable<double> OtrosDescuentos { get; set; }
        public Nullable<double> MovMenSdoTributable { get; set; }
        public Nullable<double> MovMenImptoUnico { get; set; }
        public Nullable<double> MovMenAlcLiquido { get; set; }
        public Nullable<double> MovMenAFPTotalPagada { get; set; }
        public Nullable<double> ISAPRE { get; set; }
        public Nullable<double> MovMenAFCMonto { get; set; }
        public Nullable<double> MovMenTotalMontoAPV { get; set; }
        public Nullable<double> SeguroAccidenteTrabajo { get; set; }
        public Nullable<double> MovMenSdoImponibleSIS { get; set; }
        public Nullable<double> MovMenAFCAporteEmple { get; set; }
        public Nullable<double> FondoSolidario { get; set; }
        public Nullable<double> MovMenGratificacionPagada { get; set; }
        public string GratificacionAnual { get; set; }
        public Nullable<double> MovMenAsigMovilizacionPagada { get; set; }
        public Nullable<int> MovMenAsigColacionPagada { get; set; }
        public string RebajaZonaExtrema { get; set; }
        public string BonoRentaAccesorias { get; set; }
        public string HABERES { get; set; }
        public Nullable<double> H_AGINALDO_DE_NAVIDAD { get; set; }
        public Nullable<double> H_AGUINALDO_DE_NAVIDAD { get; set; }
        public Nullable<double> H_AGUINALDO_FIESTAS_PATRIAS { get; set; }
        public Nullable<double> H_AGUINALDO_NAVIDAD { get; set; }
        public Nullable<double> H_ASIG_FAM_RETROACTIVA { get; set; }
        public Nullable<double> H_ASIGANCION_TELEFONO { get; set; }
        public Nullable<double> H_ASIGNACION_DEFUNCION { get; set; }
        public Nullable<double> H_ASIGNACION_NUPCIALIDAD { get; set; }
        public Nullable<double> H_BONO { get; set; }
        public Nullable<double> H_BONO_ADICIONAL { get; set; }
        public Nullable<double> H_BONO_DE_COLACION { get; set; }
        public Nullable<double> H_BONO_ENCARGADO { get; set; }
        public Nullable<double> H_BONO_ESPECIAL { get; set; }
        public Nullable<double> H_BONO_EXTRAORDINARIO { get; set; }
        public Nullable<double> H_BONO_INVENTARIO { get; set; }
        public Nullable<double> H_BONO_MAQUINISTA { get; set; }
        public Nullable<double> H_BONO_MATRICULA { get; set; }
        public Nullable<double> H_BONO_METAS { get; set; }
        public Nullable<double> H_BONO_MOVILIZACION { get; set; }
        public Nullable<double> H_BONO_NUPCIALIDAD { get; set; }
        public Nullable<double> H_BONO_PRODUCCION { get; set; }
        public Nullable<double> H_BONO_REEMPLAZO { get; set; }
        public Nullable<double> H_BONO_RESPONSABILIDAD { get; set; }
        public Nullable<double> H_COMISION_VENTAS { get; set; }
        public Nullable<double> H_COMISIONES { get; set; }
        public Nullable<double> H_DEVOLUCION_DESC_MES_ANT { get; set; }
        public Nullable<double> H_DIFERENCIA_MES_ANTERIOR { get; set; }
        public Nullable<double> H_MOVILIZACION { get; set; }
        public Nullable<double> H_MOVILIZACION_EXTRAORDINARIA { get; set; }
        public Nullable<double> H_PRODUCCION_UNIDADES_EQUIVALENTES { get; set; }
        public Nullable<double> H_PROMOCIONES { get; set; }
        public Nullable<double> H_SALA_CUNA { get; set; }
        public Nullable<double> H_HHEE_NORMAL { get; set; }
        public Nullable<double> H_CARGA_FAMILIAR { get; set; }
        public Nullable<double> H_CARGA_FAMILIAR_RETROACTIVA { get; set; }
        public string DESCUENTOS { get; set; }
        public Nullable<double> D_AHORRO_HABITACIONAL { get; set; }
        public Nullable<double> D_ANTICIPO_EXTRAORDINARIO { get; set; }
        public Nullable<double> D_COMPRA_LEASING { get; set; }
        public Nullable<double> D_CONVENIO_DENTAL { get; set; }
        public Nullable<double> D_DONACION { get; set; }
        public Nullable<double> D_FACTURAS { get; set; }
        public Nullable<double> D_GIMNASIO_ENERGY { get; set; }
        public Nullable<double> D_GIMNASIO_PACIFIC { get; set; }
        public Nullable<double> D_OPTICA { get; set; }
        public Nullable<double> D_OTRO_DESCUENTO { get; set; }
        public Nullable<double> D_OTROS_DESCUENTOS { get; set; }
        public Nullable<double> D_PRESTAMO_BCO_CHILE { get; set; }
        public Nullable<double> D_PRESTAMO_CAJA_LOS_ANDES { get; set; }
        public Nullable<double> D_PRESTAMO_EMPRESA_1 { get; set; }
        public Nullable<double> D_PRESTAMO_EMPRESA_2 { get; set; }
        public Nullable<double> D_SALCOBRAND { get; set; }
        public Nullable<double> D_SEGURO_COMPLEMENTARIO { get; set; }
        public Nullable<double> D_TELEFONO { get; set; }
        public Nullable<double> D_UNIFORMES { get; set; }
        public Nullable<double> D_VENTA_DE_BODEGA { get; set; }
        public Nullable<double> D_DESCUENTO_TAG { get; set; }
        public Nullable<double> D_CTA_AHORRO { get; set; }
        public Nullable<double> D_Ausente { get; set; }
        public Nullable<double> D_licencia { get; set; }
        public Nullable<double> P1 { get; set; }
        public Nullable<double> P2 { get; set; }
    }
}
