//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALANA_HABERES
    {
        public string Empresa { get; set; }
        public short Año { get; set; }
        public short Mes { get; set; }
        public string Rut { get; set; }
        public string Apellido_P { get; set; }
        public string Apellido_M { get; set; }
        public string Nombre { get; set; }
        public string TIPO_HABER_DESCUENTO { get; set; }
        public string CentroCosto { get; set; }
        public string DEPARTAMENTO { get; set; }
        public Nullable<double> AGINALDO_DE_NAVIDAD { get; set; }
        public Nullable<double> AGUINALDO_DE_NAVIDAD { get; set; }
        public Nullable<double> AGUINALDO_FIESTAS_PATRIAS { get; set; }
        public Nullable<double> AGUINALDO_NAVIDAD { get; set; }
        public Nullable<double> ASIG__FAM__RETROACTIVA { get; set; }
        public Nullable<double> ASIGANCION_TELEFONO { get; set; }
        public Nullable<double> ASIGNACION_DEFUNCION { get; set; }
        public Nullable<double> ASIGNACION_NUPCIALIDAD { get; set; }
        public Nullable<double> BONO { get; set; }
        public Nullable<double> BONO_ADICIONAL { get; set; }
        public Nullable<double> BONO_DE_COLACION { get; set; }
        public Nullable<double> BONO_ENCARGADO { get; set; }
        public Nullable<double> BONO_ESPECIAL { get; set; }
        public Nullable<double> BONO_EXTRAORDINARIO { get; set; }
        public Nullable<double> BONO_INVENTARIO { get; set; }
        public Nullable<double> BONO_MAQUINISTA { get; set; }
        public Nullable<double> BONO_MATRICULA { get; set; }
        public Nullable<double> BONO_METAS { get; set; }
        public Nullable<double> BONO_MOVILIZACION { get; set; }
        public Nullable<double> BONO_NUPCIALIDAD { get; set; }
        public Nullable<double> BONO_PRODUCCION { get; set; }
        public Nullable<double> BONO_REEMPLAZO { get; set; }
        public Nullable<double> BONO_RESPONSABILIDAD { get; set; }
        public Nullable<double> COLACION { get; set; }
        public Nullable<double> COMISION_VENTAS { get; set; }
        public Nullable<double> COMISIONES { get; set; }
        public Nullable<double> DEVOLUCION_DESC__MES_ANT_ { get; set; }
        public Nullable<double> DIFERENCIA_MES_ANTERIOR { get; set; }
        public Nullable<double> MOVILIZACION { get; set; }
        public Nullable<double> MOVILIZACION_EXTRAORDINARIA { get; set; }
        public Nullable<double> PRODUCCION_UNIDADES_EQUIVALENTES { get; set; }
        public Nullable<double> PROMOCIONES { get; set; }
        public Nullable<double> SALA_CUNA { get; set; }
        public Nullable<double> SEMANA_CORRIDA { get; set; }
        public Nullable<double> SUELDO_DIARIO { get; set; }
        public Nullable<double> SUELDO_DIARO { get; set; }
    }
}
