//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LProsud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TRANSPORTES_CHOFERES
    {
        public string Empresa { get; set; }
        public string RutTrans { get; set; }
        public short ExtranjeroTrans { get; set; }
        public string NombreTrans { get; set; }
        public string RutChofer { get; set; }
        public string NombreChofer { get; set; }
        public Nullable<int> Celular { get; set; }
    }
}
